import type { MeriendaRoute, Place } from "@/lib/types";

const img = {
  haiti:
    "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1400&q=80",
  coqueta:
    "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1400&q=80",
  alba:
    "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1400&q=80",
  ensueno:
    "https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=1400&q=80",
  punto:
    "https://images.unsplash.com/photo-1445116572660-236099ec97a0?auto=format&fit=crop&w=1400&q=80",
  cinco:
    "https://images.unsplash.com/photo-1493857671505-72967e2e2760?auto=format&fit=crop&w=1400&q=80",
  bendito:
    "https://images.unsplash.com/photo-1453614512568-7af50c6d2afb?auto=format&fit=crop&w=1400&q=80",
  franklin:
    "https://images.unsplash.com/photo-1521017432531-fbd92d768814?auto=format&fit=crop&w=1400&q=80",
  bonito:
    "https://images.unsplash.com/photo-1511920170033-f8396924c348?auto=format&fit=crop&w=1400&q=80",
  clapton:
    "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1400&q=80",
  montanas:
    "https://images.unsplash.com/photo-1481391319762-47dff72954d9?auto=format&fit=crop&w=1400&q=80",
  lena:
    "https://images.unsplash.com/photo-1497534446932-c925b458314e?auto=format&fit=crop&w=1400&q=80",
  cleta:
    "https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=1400&q=80",
  edesia:
    "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=1400&q=80",
  elizardo:
    "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1400&q=80",
  delicias:
    "https://images.unsplash.com/photo-1464305795204-6f5bbfc7fb81?auto=format&fit=crop&w=1400&q=80",
  isalu:
    "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=1400&q=80",
  juana:
    "https://images.unsplash.com/photo-1501339845172-3153c2184c68?auto=format&fit=crop&w=1400&q=80",
  parador:
    "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1400&q=80",
  rodeo:
    "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1400&q=80",
  lisandro:
    "https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=1400&q=80",
  gardel:
    "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=1400&q=80",
  comidas:
    "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=1400&q=80",
  marias:
    "https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=1400&q=80",
  victoria:
    "https://images.unsplash.com/photo-1571115177098-24ec42ed204d?auto=format&fit=crop&w=1400&q=80",
  vallecito:
    "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1400&q=80",
  grill:
    "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=1400&q=80",
  pasta:
    "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?auto=format&fit=crop&w=1400&q=80",
  asado:
    "https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?auto=format&fit=crop&w=1400&q=80",
  regional:
    "https://images.unsplash.com/photo-1544025162-d76640320d2a?auto=format&fit=crop&w=1400&q=80",
};

export const places: Place[] = [
  {
    slug: "cafe-haiti",
    name: "Café Haití",
    kind: "cafe",
    department: "ullum",
    locality: "Ullum",
    address:
      "Ubicación a confirmar — circula por redes y de boca en boca. Casi no aparece en el mapa.",
    addressConfirmed: false,
    hours: "Confirmá por redes antes de ir: horarios de pueblo, a veces cierra sin aviso.",
    visibility: "redes",
    sources: ["redes", "recorrido", "boca-en-boca"],
    blurb:
      "El ejemplo de por qué hace falta esta guía: un café que la gente del departamento conoce y el resto de San Juan no.",
    story:
      "En los recorridos por Ullum y otros departamentos alejados del centro aparecen locales así: una vidriera chica, medialunas a la tarde, un cartel escrito a mano. Café Haití casi no está en el mapa, no tiene ficha turística y igual se llena los sábados porque alguien lo recomendó. Esta ficha está incompleta a propósito: si sabés la calle, el horario o el @, sumalo. El punto no es “descubrirlo para turistas”: es que un sanjuanino de Capital también pueda merendar ahí.",
    orderThis: ["Café con leche", "Tostado", "Lo que haya salido del horno"],
    tags: ["poco-indexado", "redes", "merienda", "departamento"],
    image: img.haiti,
    imageAlt: "Taza de café sobre mesa de madera",
    mapsQuery: "Ullum San Juan café",
  },
  {
    slug: "la-coqueta",
    name: "La Coqueta",
    kind: "casa-de-te",
    department: "zonda",
    locality: "Villa Basilio Nievas · Sierras Azules",
    address: "Ruta Provincial 12 esquina Sarmiento, Zonda",
    addressConfirmed: true,
    hours: "Lun–mié 10:30 a 18 · Jue cerrado · Vie–dom 10:30 a 02:00. Confirmá merienda por redes.",
    phone: "+54 264 439-9862",
    handle: "lacoquetasanjuan",
    visibility: "conocido",
    sources: ["redes", "google", "recorrido"],
    blurb: "Restaurante de campo y casa de té a 15 minutos de la ciudad, con merienda criolla y cerro de fondo.",
    story:
      "Andrea Coria lleva más de 15 años en Zonda. La Coqueta empezó cuando en el valle casi no había nada y hoy es el ancla del polo gastronómico (junto a Sierras Azules y Cielo Alto). No es un secreto absoluto, pero mucha gente de Capital sigue sin cruzar el dique a merendar. Vale el viaje: desayuno, almuerzo y merienda con paisaje, no con vidriera de peatonal.",
    orderThis: ["Merienda criolla", "Infusión", "Algo a las brasas si llegás al mediodía"],
    tags: ["merienda", "cerro", "patio", "fin-de-semana", "familia", "almuerzo"],
    image: img.coqueta,
    imageAlt: "Cerros y valle de montaña al atardecer",
    mapsQuery: "La Coqueta RP12 Zonda San Juan",
  },
  {
    slug: "el-alba-zonda",
    name: "El Alba",
    kind: "comedor",
    department: "zonda",
    locality: "Zonda",
    address: "9 de Julio y Matías Sánchez, Zonda",
    addressConfirmed: true,
    hours: "Horario irregular: suele abrir lun–mié y domingo desde las 13. Jueves a sábado a menudo cerrado. Confirmá.",
    visibility: "poco-conocido",
    sources: ["recorrido", "redes", "google"],
    blurb: "Casa de campo con postres y vista. Hermoso, pero hay que ir con el horario chequeado: no es una confitería de 8 a 21.",
    story:
      "El Alba aparece cuando recorrés Zonda y preguntás “¿dónde se merienda por acá?”. El lugar es precioso; la carta es corta y el servicio de merienda a veces se hace esperar. Lo incluimos porque es típico de los departamentos: un local que existe, que se ve en fotos, y que Google no te explica cuándo está abierto.",
    orderThis: ["Postre de la casa", "Café", "Entrada para picar"],
    tags: ["cerro", "postres", "horario-raro", "campo"],
    image: img.alba,
    imageAlt: "Montañas al sol",
    mapsQuery: "El Alba restaurante 9 de Julio Zonda San Juan",
  },
  {
    slug: "comidas-zonda",
    name: "COMIDAS..",
    kind: "comedor",
    department: "zonda",
    locality: "Zonda",
    address: "Zonda — ficha digital casi nula; preguntá en el pueblo o mirá si está la luz prendida.",
    addressConfirmed: false,
    hours: "Vie–dom de noche (aprox. 20 a 00). Cerrado lun–jue.",
    visibility: "redes",
    sources: ["recorrido", "boca-en-boca"],
    blurb: "El nombre es el menú. Pizza a la piedra y platos de pueblo. Casi no tiene redes ni web: se encuentra yendo.",
    story:
      "COMIDAS.. es el extremo de lo que esta app quiere juntar: un local con nombre literal, horario de fin de semana y presencia digital cercana a cero. Quienes viven en Zonda lo tienen; quienes viven en Capital no. Si pasás el sábado a la noche, es una parada genuina.",
    orderThis: ["Pizza a la piedra", "Lo que salga"],
    tags: ["redes", "fin-de-semana", "poco-indexado", "pueblo"],
    image: img.comidas,
    imageAlt: "Pizza recién horneada",
    mapsQuery: "COMIDAS Zonda San Juan",
  },
  {
    slug: "parque-parador-zonda",
    name: "Parque Parador de Montaña",
    kind: "confiteria",
    department: "zonda",
    locality: "Quebrada de Zonda",
    address: "Parque / parador de montaña, Quebrada de Zonda",
    addressConfirmed: true,
    hours: "Varía según temporada y concesión. Confirmá el día que vayas a la quebrada.",
    visibility: "poco-conocido",
    sources: ["recorrido", "redes"],
    blurb: "Parador de la quebrada: café con vista, no con branding. Ideal si ya ibas al parque y no querías volver al centro con hambre.",
    story:
      "La Quebrada de Zonda es uno de los paisajes más queridos de la provincia. El parador y la hostería Sarmiento (en proceso de reconcesión) son exactamente el tipo de confitería que el turista busca y el local a veces olvida: merienda mirando el cerro. Lo listamos para que no dependa de que alguien lo suba a las redes.",
    orderThis: ["Café", "Tostado", "Agua + sombra"],
    tags: ["cerro", "merienda", "paseo", "quebrada"],
    image: img.parador,
    imageAlt: "Paisaje de montaña con cielo abierto",
    mapsQuery: "Parque Parador de Montaña Quebrada de Zonda San Juan",
  },
  {
    slug: "gardel-confiteria",
    name: "Gardel Confitería",
    kind: "confiteria",
    department: "zonda",
    locality: "Villa Basilio Nievas",
    address: "Villa Basilio Nievas, Zonda (camino sin nombre en Maps)",
    addressConfirmed: true,
    hours: "Mié–sáb 20:00 a 00:30. Lun, mar y dom cerrado. No es merienda: es noche.",
    phone: "+54 264 455-3794",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Se llama confitería y es una lomoteca de pueblo. Abre de noche. Lo metemos porque el nombre engaña y la gente de Zonda lo tiene como clásico.",
    story:
      "No todas las “confiterías” de departamento son medialunas a las 17. Gardel es el caso inverso: un local de lomos enormes, horario nocturno, y un nombre que en Capital nadie busca. Si armás una guía honesta, también tenés que decir cuándo NO ir a merendar.",
    orderThis: ["Lomo", "Cerveza"],
    tags: ["noche", "lomo", "pueblo", "no-merienda", "cena"],
    image: img.gardel,
    imageAlt: "Sándwich abundante",
    mapsQuery: "Gardel Confitería Villa Basilio Nievas Zonda",
  },
  {
    slug: "el-ensueno-ullum",
    name: "Comedor El Ensueño",
    kind: "comedor",
    department: "ullum",
    locality: "Ullum · Barrio Colón",
    address: "Calle San Antonio, Barrio Colón, Ullum",
    addressConfirmed: true,
    hours: "Lun–jue 8 a 14:30 y 20 a 23 · Domingo 9 a 14:30. Confirmá lunes feriados.",
    phone: "+54 264 414-1210",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Bodegón de Ullum que abre de mañana: desayuno y café sin pretender ser cafetería de especialidad.",
    story:
      "El Ensueño es de los pocos lugares de Ullum que aparecen con dirección. Sirve desayuno, almuerzo y cena, porciones de pueblo. Para quien recorre el dique y vuelve con hambre, es más útil que cualquier café de la peatonal. No lo vas a encontrar buscando “brunch San Juan”.",
    orderThis: ["Desayuno", "Comida casera", "Café"],
    tags: ["desayuno", "familia", "dique", "bodegon"],
    image: img.ensueno,
    imageAlt: "Interior cálido de cafetería",
    mapsQuery: "Comedor El Ensueño San Antonio Ullum San Juan",
  },
  {
    slug: "punto-encuentro-lm",
    name: "Punto de Encuentro L&M",
    kind: "cafe",
    department: "ullum",
    locality: "Ullum",
    address: "Ullum — maxikiosco / café de pueblo. Casi sin ficha digital.",
    addressConfirmed: false,
    hours: "Horario de comercio de pueblo. Preguntá en el lugar.",
    visibility: "redes",
    sources: ["recorrido", "boca-en-boca"],
    blurb: "Maxikiosco que también es café. Cero redes activas, cero web. Se encuentra recorriendo Ullum.",
    story:
      "Hay un tipo de local sanjuanino que Google no sabe clasificar: vende galletitas, sirve un café, a veces un lomo, y es el punto de encuentro del barrio. Punto de Encuentro L&M es eso. Lo listamos porque si solo indexamos “cafeterías de especialidad”, Ullum desaparece del mapa.",
    orderThis: ["Café", "Algo de kiosco", "Lo que tengan caliente"],
    tags: ["poco-indexado", "pueblo", "redes", "barrio"],
    image: img.punto,
    imageAlt: "Barra de café sencilla",
    mapsQuery: "Punto de Encuentro L&M Ullum San Juan",
  },
  {
    slug: "cinco-uno",
    name: "Cinco Uno Cafetería",
    kind: "cafe",
    department: "rawson",
    locality: "Villa Krause",
    address: "Pasaje Argentino 4288 Sur, Villa Krause",
    addressConfirmed: true,
    hours: "Lun–vie 8–13 y 18–21:30 · Sáb 8:30–13:30 y 18–21:30. Domingo: confirmá por redes.",
    phone: "+54 264 509-9996",
    handle: "cincouno_cafeteria",
    visibility: "redes",
    sources: ["redes", "recorrido"],
    blurb: "Cafetería de Villa Krause que se mueve mucho por redes: desayunos, malteadas y sándwich de campo.",
    story:
      "Cinco Uno es el caso Capital-pero-no: está en el Gran San Juan y aun así vive en las redes. Desayunos, malteadas, sándwich de campo, tartas. Lo conocimos como se conocen estos lugares: un @, una recomendación, un pasaje que no es avenida. Si buscás “cafeterías San Juan” te aparecen los de Tucumán y España; este no.",
    orderThis: ["Sándwich de campo", "Malteada", "Café", "Tarta"],
    tags: ["redes", "desayuno", "merienda", "villa-krause"],
    image: img.cinco,
    imageAlt: "Cafetería iluminada de noche",
    mapsQuery: "Cinco Uno Cafetería Pasaje Argentino Villa Krause San Juan",
  },
  {
    slug: "entre-montanas",
    name: "Entre Montañas, casa de té y café",
    kind: "casa-de-te",
    department: "rivadavia",
    locality: "Rivadavia",
    address: "Av. Libertador Gral. San Martín 3790, Rivadavia",
    addressConfirmed: true,
    hours: "Mar–dom 9–13 y 17–22 · Lunes 17–22. Sábado a veces corrido.",
    phone: "+54 264 423-8556",
    visibility: "poco-conocido",
    sources: ["redes", "google", "recorrido"],
    blurb: "Pastelería casera, infusiones y almuerzos livianos sobre Libertador. Más casa de té que café de moda.",
    story:
      "Rivadavia tiene una avenida entera de meriendas que Capital trata como “allá”. Entre Montañas es regional: scones, budines, infusiones, empanadas. Si armás una tarde hacia el oeste, es una parada clara antes o después de Zonda.",
    orderThis: ["Scones", "Infusión de la casa", "Budín", "Jugo natural"],
    tags: ["merienda", "pasteleria", "te", "libertador"],
    image: img.montanas,
    imageAlt: "Torta y chocolate",
    mapsQuery: "Entre Montañas casa de té Libertador 3790 Rivadavia San Juan",
  },
  {
    slug: "casa-lena",
    name: "Casa Lena",
    kind: "cafe",
    department: "rivadavia",
    locality: "Rivadavia",
    address: "Saavedra Norte 125, Rivadavia",
    addressConfirmed: true,
    hours: "Mar–dom 9–13 y 18–22. Lunes cerrado. Horarios según redes.",
    phone: "+54 264 662-4536",
    handle: "casalenasj",
    visibility: "poco-conocido",
    sources: ["redes", "google"],
    blurb: "Café de especialidad y brunch en Rivadavia, con mucha vida en redes.",
    story:
      "Casa Lena es de los pocos “coffee brunch” fuera de Capital. Saavedra Norte no es peatonal Tucumán: hay que ir a propósito. Café de especialidad, horarios partidos, y un @ que es la fuente de verdad de la carta.",
    orderThis: ["Café de especialidad", "Brunch", "Tostadas"],
    tags: ["especialidad", "brunch", "redes", "merienda"],
    image: img.lena,
    imageAlt: "Café latte en mesa",
    mapsQuery: "Casa Lena Saavedra Norte 125 Rivadavia San Juan",
  },
  {
    slug: "isalu-pasteleria",
    name: "Isalú Pastelería",
    kind: "pasteleria",
    department: "rivadavia",
    locality: "Rivadavia",
    address: "Av. Libertador Gral. San Martín 7956, Rivadavia",
    addressConfirmed: true,
    hours: "Consultá por teléfono: +54 264 570-5551. Suele haber mostrador y delivery.",
    phone: "+54 264 570-5551",
    visibility: "poco-conocido",
    sources: ["google", "recorrido"],
    blurb: "Pastelería de Libertador: tortas, tartas, muffins. Más mostrador que salón, útil si vas de paso al oeste.",
    story:
      "No todo es café de especialidad. Isalú es el mostrador de barrio al que vas a buscar una tarta y te tomás algo si hay mesas. Este tipo de local es el tejido real de Rivadavia y casi nunca entra en “las 10 cafeterías de San Juan”.",
    orderThis: ["Tarta", "Torta", "Café para llevar"],
    tags: ["pasteleria", "para-llevar", "libertador"],
    image: img.isalu,
    imageAlt: "Torta de chocolate",
    mapsQuery: "Isalú Pastelería Libertador 7956 Rivadavia San Juan",
  },
  {
    slug: "bendito-cafe",
    name: "Bendito Café",
    kind: "cafe",
    department: "capital",
    locality: "Capital",
    address: "Rivadavia 249, pasillo interior, San Juan",
    addressConfirmed: true,
    hours: "Lun–vie 7 a 21 · Sáb 8:30–13 y 17–21 · Dom cerrado.",
    phone: "+54 264 626-7007",
    visibility: "conocido",
    sources: ["google", "redes"],
    blurb: "Café de especialidad escondido en un pasillo del centro. Desayuno, brunch y almuerzo, lejos del ruido de la calle.",
    story:
      "Bendito es de Capital, pero ilustra el otro problema: incluso en el centro hay locales que no se ven desde la vereda. Está en un pasillo que conecta dos calles. Si esta guía solo listara Zonda, mentiría: el mapa incompleto también está a tres cuadras de la peatonal.",
    orderThis: ["Café de especialidad", "Brunch", "Pastelería"],
    tags: ["especialidad", "escondido", "desayuno", "centro"],
    image: img.bendito,
    imageAlt: "Café en interior iluminado",
    mapsQuery: "Bendito Café Rivadavia 249 San Juan",
  },
  {
    slug: "cafe-franklin",
    name: "Café Franklin",
    kind: "confiteria",
    department: "capital",
    locality: "Capital",
    address: "Francisco N. Laprida 63 Este, San Juan",
    addressConfirmed: true,
    hours: "Lun–vie 7:30–14 y 16:30/18–21 · Sáb similar · Dom cerrado.",
    visibility: "poco-conocido",
    sources: ["google", "recorrido"],
    blurb: "Confitería clásica cerca de la biblioteca: medialunas, suspiro de limón y café de toda la vida.",
    story:
      "Franklin no es un local de moda. Es el café de Laprida, con horario partido y cierre domingo —muy sanjuanino—. Lo incluimos para equilibrar: no todo lo “poco conocido” está en un departamento lejano; a veces está a una cuadra y no es tendencia.",
    orderThis: ["Medialunas", "Café con leche", "Suspiro de limón"],
    tags: ["clasico", "merienda", "centro", "confiteria"],
    image: img.franklin,
    imageAlt: "Salón de café clásico",
    mapsQuery: "Café Franklin Laprida 63 Este San Juan",
  },
  {
    slug: "bonito-cafe",
    name: "Bonito Café",
    kind: "cafe",
    department: "capital",
    locality: "Capital",
    address: "Av. España Sur 186, San Juan",
    addressConfirmed: true,
    hours: "Todos los días desde las 8 / 8:30 hasta 22:30 o 23.",
    phone: "+54 264 460-0888",
    visibility: "conocido",
    sources: ["google", "redes"],
    blurb: "Café amplio sobre España: desayuno, merienda y platos para compartir. De los más visibles del centro.",
    story:
      "Bonito es un café amplio sobre España: desayuno, merienda y platos para compartir. De los más visitados de Capital, y parte de esta guía como el resto.",
    orderThis: ["Bonito desayuno", "Flat white", "Merienda para compartir"],
    tags: ["centro", "desayuno", "merienda", "amplio"],
    image: img.bonito,
    imageAlt: "Café espresso",
    mapsQuery: "Bonito Café España Sur 186 San Juan",
  },
  {
    slug: "clapton",
    name: "Clapton Café y Vinos",
    kind: "cafe",
    department: "capital",
    locality: "Capital",
    address: "Tucumán Sur 230, San Juan",
    addressConfirmed: true,
    hours: "Consultá: peatonal Tucumán, horarios amplios de café y vinos.",
    phone: "+54 264 422-8786",
    visibility: "conocido",
    sources: ["google", "redes"],
    blurb: "Café de especialidad en Tucumán, con terraza. El circuito que sí aparece cuando buscás “cafeterías San Juan”.",
    story:
      "Clapton está en Tucumán con café de especialidad y terraza. Lo listamos junto a los locales de departamento porque la guía es de toda la provincia, no de un solo circuito.",
    orderThis: ["Café de origen", "Tostadas", "Algo de la terraza"],
    tags: ["especialidad", "centro", "terraza", "vinos"],
    image: img.clapton,
    imageAlt: "Granos de café tostado",
    mapsQuery: "Clapton Café Tucumán Sur 230 San Juan",
  },
  {
    slug: "cleta-cafe",
    name: "Cleta Café",
    kind: "cafe",
    department: "capital",
    locality: "Capital",
    address: "Av. Guillermo Rawson Sur 396, San Juan",
    addressConfirmed: true,
    hours: "Lun–vie 8:30–12:45 y 17–20:30 · Sáb solo mañana · Dom cerrado.",
    visibility: "poco-conocido",
    sources: ["google", "recorrido"],
    blurb: "Café sobre Rawson, horario partido y domingo cerrado. Fuera de la peatonal, cerca del estadio.",
    story:
      "Cleta está en Capital y igual se siente de barrio: cierra temprano, no abre domingo, y no está en Tucumán. Es el tipo de ficha que una guía de “los mejores cafés” se salta y un vecino usa todas las semanas.",
    orderThis: ["Café", "Merienda rápida"],
    tags: ["barrio", "horario-partido", "capital"],
    image: img.cleta,
    imageAlt: "Café en grano",
    mapsQuery: "Cleta Café Rawson Sur 396 San Juan",
  },
  {
    slug: "las-delicias",
    name: "Las Delicias Confitería",
    kind: "confiteria",
    department: "capital",
    locality: "Capital",
    address: "Av. Rioja Sur 148, San Juan",
    addressConfirmed: true,
    hours: "Lun–sáb 8–13 y 17–21 · Domingo cerrado.",
    phone: "+54 264 422-5519",
    visibility: "conocido",
    sources: ["google"],
    blurb: "Confitería de Rioja, frente a la Capilla San Clemente. Tradición de mostrador y salón.",
    story:
      "Las Delicias es el arquetipo de confitería sanjuanina de Capital: horario partido, domingo cerrado, facturas y café. Sirve de ancla para quien extraña “una confitería de verdad” y no un brunch.",
    orderThis: ["Facturas", "Café con leche", "Torta"],
    tags: ["confiteria", "clasico", "centro", "merienda"],
    image: img.delicias,
    imageAlt: "Facturas y pastelería",
    mapsQuery: "Las Delicias Confitería Rioja Sur 148 San Juan",
  },
  {
    slug: "juana-house",
    name: "Juana House",
    kind: "cafe",
    department: "capital",
    locality: "Desamparados",
    address: "Del Bono entre Juana Manso y Cornelio Saavedra, Desamparados",
    addressConfirmed: true,
    hours: "Según Diario de Cuyo: de 9 a 22. Confirmá por redes.",
    visibility: "redes",
    sources: ["redes"],
    blurb: "Café de especialidad en Desamparados. Sale más en redes que en el mapa turístico del centro.",
    story:
      "Desamparados es Capital y no es el microcentro. Juana House aparece en directorios locales y en redes, no en las listas de “qué hacer en San Juan”. Lo listamos para empujar el mapa dos kilómetros al este.",
    orderThis: ["Café de especialidad", "Brunch chico"],
    tags: ["especialidad", "redes", "desamparados"],
    image: img.juana,
    imageAlt: "Interior de café moderno",
    mapsQuery: "Juana House Del Bono Desamparados San Juan",
  },
  {
    slug: "victoria-igualada",
    name: "Victoria Igualada",
    kind: "pasteleria",
    department: "capital",
    locality: "Capital",
    address: "Av. Libertador Gral. San Martín 1730 Oeste, San Juan",
    addressConfirmed: true,
    hours: "Consultá redes: salón y retiro. Tel. +54 264 580-3177.",
    phone: "+54 264 580-3177",
    visibility: "poco-conocido",
    sources: ["redes"],
    blurb: "Pastelería artesanal que se pide por redes. El salón, si abre, es un extra.",
    story:
      "Hay un circuito entero de pastelerías sanjuaninas que no son “local a la calle”: se encargan por WhatsApp, se retiran, a veces hay dos mesas. Victoria Igualada representa ese formato. Si esta guía solo listara salones, perderíamos la mitad de la oferta real.",
    orderThis: ["Torta de la semana", "Alfajores", "Café si hay salón"],
    tags: ["pasteleria", "redes", "encargue", "desamparados"],
    image: img.victoria,
    imageAlt: "Torta artesanal",
    mapsQuery: "Victoria Igualada Libertador 1730 Oeste San Juan",
  },
  {
    slug: "edesia-jachal",
    name: "Edesia",
    kind: "cafe",
    department: "jachal",
    locality: "San José de Jáchal",
    address: "Domingo F. Sarmiento 690, San José de Jáchal",
    addressConfirmed: true,
    hours: "Lun–vie 8:30–12 y 17:30–21:30 · Sáb–dom 9:30–13 y 17:30–21:30.",
    phone: "+54 264 471-4968",
    visibility: "poco-conocido",
    sources: ["redes", "google", "recorrido"],
    blurb: "Café de especialidad en Jáchal. Para Capital es “el norte”; para Jáchal es el lugar a merendar.",
    story:
      "Edesia muestra que el café de especialidad también está en Jáchal. Tostadas, brunch y café bien hecho, en Sarmiento 690. Si alguien arma un finde al norte y solo busca parrilla, se pierde la merienda.",
    orderThis: ["Café de especialidad", "Tostada", "Brunch"],
    tags: ["especialidad", "norte", "merienda", "viaje"],
    image: img.edesia,
    imageAlt: "Taza de espresso",
    mapsQuery: "Edesia café Sarmiento 690 San José de Jáchal",
  },
  {
    slug: "marias-jachal",
    name: "Marías Restó Café Bar",
    kind: "cafe",
    department: "jachal",
    locality: "San José de Jáchal",
    address: "San José de Jáchal — restó café de pueblo.",
    addressConfirmed: false,
    hours: "Consultá el día: horarios de pueblo del norte.",
    visibility: "poco-conocido",
    sources: ["redes", "recorrido"],
    blurb: "Café-bar de Jáchal que aparece en directorios locales y poco más. Complemento de Edesia para un día en el norte.",
    story:
      "Marías es el otro polo de Jáchal: menos “especialidad”, más restó café. Lo sumamos porque un departamento no puede tener una sola ficha y pretender que el mapa está completo.",
    orderThis: ["Café", "Algo salado"],
    tags: ["pueblo", "norte", "redes"],
    image: img.marias,
    imageAlt: "Café filtrado",
    mapsQuery: "Marías Restó Café Bar Jáchal San Juan",
  },
  {
    slug: "don-elizardo",
    name: "Don Elizardo, casa de té",
    kind: "casa-de-te",
    department: "calingasta",
    locality: "Barreal",
    address: "Barreal, Calingasta — casa de té familiar (Liliana y Rebeca).",
    addressConfirmed: true,
    hours: "Pensado para desayunos y meriendas de quien llega a Barreal. Confirmá el día anterior.",
    visibility: "poco-conocido",
    sources: ["recorrido", "boca-en-boca", "redes"],
    blurb: "Clásico familiar de Barreal: desayuno regional con cordillera. No es un café de Capital transplantado.",
    story:
      "Don Elizardo aparece en los circuitos turísticos de Calingasta y aun así mucha gente de San Juan ciudad no lo tiene en el radar. Desayuno regional, emprendimiento familiar, Barreal. Si el finde es Pampa del Leoncito, merendá acá —no en una estación de servicio de la ruta.",
    orderThis: ["Desayuno regional", "Té", "Algo casero"],
    tags: ["casa-de-te", "barreal", "familia", "viaje", "cordillera"],
    image: img.elizardo,
    imageAlt: "Mesa servida para desayuno",
    mapsQuery: "Don Elizardo casa de té Barreal Calingasta",
  },
  {
    slug: "don-lisandro",
    name: "Don Lisandro",
    kind: "confiteria",
    department: "calingasta",
    locality: "Barreal",
    address: "Calle San Martín 441 Este, Barreal",
    addressConfirmed: true,
    hours: "Temporada de pueblo y jardín. Consultá +54 9 264 505-9122.",
    phone: "+54 9 264 505-9122",
    visibility: "poco-conocido",
    sources: ["redes", "recorrido"],
    blurb: "Restó, heladería artesanal y jardín en Barreal. Postre o café después de la Pampa del Leoncito.",
    story:
      "Don Lisandro mezcla comida de pueblo, helado artesanal y patio. No es solo “un café”: es una razón para quedarse en Barreal a la tarde. Calingasta queda lejos para ir “a ver si está abierto”; por eso la ficha avisa que hay que confirmar.",
    orderThis: ["Helado artesanal", "Postre", "Café"],
    tags: ["helado", "barreal", "patio", "viaje"],
    image: img.lisandro,
    imageAlt: "Helado artesanal",
    mapsQuery: "Don Lisandro Barreal Calingasta San Juan",
  },
  {
    slug: "rodeo-cafe",
    name: "Rodeo Café Restó Bar",
    kind: "cafe",
    department: "iglesia",
    locality: "Rodeo",
    address: "Rodeo, Iglesia (ex Surfera)",
    addressConfirmed: true,
    hours: "Temporada de montaña. Confirmá por redes del pueblo.",
    visibility: "redes",
    sources: ["redes", "recorrido"],
    blurb: "Parada de Rodeo. La oferta de Iglesia se entera por redes del pueblo, no buscando “cafeterías San Juan”.",
    story:
      "Iglesia es el ejemplo extremo: a horas de Capital, con un puñado de restós. Rodeo Café (ex Surfera) es de los pocos que figuran como café-bar. Si vas a Las Flores o al Parque Nacional San Guillermo, esta ficha evita que meriendes un paquete de galletitas en la ruta sin saber que había un local.",
    orderThis: ["Café", "Comida de parador"],
    tags: ["montana", "redes", "viaje", "rodeo"],
    image: img.rodeo,
    imageAlt: "Camino de montaña",
    mapsQuery: "Rodeo Café Restó Bar Rodeo Iglesia San Juan",
  },
  {
    slug: "confiteria-vallecito",
    name: "Confitería de Vallecito",
    kind: "confiteria",
    department: "caucete",
    locality: "Vallecito · Paraje Difunta Correa",
    address: "Paraje Difunta Correa, Vallecito, Caucete",
    addressConfirmed: true,
    hours: "Días de movimiento del santuario y fines de semana. Confirmá si viajás entre semana.",
    visibility: "poco-conocido",
    sources: ["recorrido", "redes"],
    blurb: "Confitería de ruta en el paraje de Difunta Correa. El turista para; el de Capital no la tiene como “salida a merendar”.",
    story:
      "Vallecito es un flujo enorme de gente y, aun así, la confitería del paraje no entra en ninguna guía de cafés. Es oferta real: café, facturas, algo salado, en el este de la provincia. Esta app también es para el que vuelve de Caucete y no quiere llegar a Capital para sentarse.",
    orderThis: ["Café", "Facturas", "Algo de ruta"],
    tags: ["ruta", "santuario", "este", "confiteria"],
    image: img.vallecito,
    imageAlt: "Mesa de comida de camino",
    mapsQuery: "Confitería Vallecito Difunta Correa Caucete San Juan",
  },
  {
    slug: "yo-tengo-fe",
    name: "Confitería Yo Tengo Fe",
    kind: "confiteria",
    department: "iglesia",
    locality: "Rodeo",
    address: "Av. Santo Domingo, Rodeo, Iglesia",
    addressConfirmed: true,
    hours: "Lun–sáb desde ~10:30. Domingo más tarde. Confirmá si vas a merendar: también funciona como resto y bar.",
    phone: "+54 264 445-6888",
    visibility: "poco-conocido",
    sources: ["recorrido", "redes", "google"],
    blurb: "Confitería de Rodeo: café con medialunas a la mañana, comida de pueblo el resto del día.",
    story:
      "En Iglesia Google casi no lista “cafeterías”. Yo Tengo Fe está sobre Santo Domingo y arranca el día como confitería. Si vas a Cuesta del Viento, es una parada de merienda real, no un parador de ruta anónimo.",
    orderThis: ["Café con medialunas", "Confitería", "Comida casera"],
    tags: ["confiteria", "rodeo", "montana", "merienda"],
    image: img.rodeo,
    imageAlt: "Camino de montaña",
    mapsQuery: "Confitería Yo Tengo Fe Santo Domingo Rodeo Iglesia San Juan",
  },
  {
    slug: "inna-cafe",
    name: "Inna Café",
    kind: "confiteria",
    department: "valle-fertil",
    locality: "Valle Fértil",
    address: "Laprida y Mendoza, Valle Fértil",
    addressConfirmed: true,
    hours: "Confirmá el día: ficha de turismo provincial, teléfono +54 9 380 428-7003.",
    phone: "+54 9 380 428-7003",
    visibility: "poco-conocido",
    sources: ["recorrido", "redes"],
    blurb: "Confitería listada por Turismo San Juan en Valle Fértil. Camino a Ischigualasto hay que merendar en algún lado.",
    story:
      "Valle Fértil aparece en las guías por los comedores, no por el café. Inna Café está en el directorio oficial (Laprida y Mendoza) y igual casi no circula si buscás “cafeterías San Juan”. Lo sumamos para que el este de la provincia no quede en blanco.",
    orderThis: ["Café", "Merienda"],
    tags: ["confiteria", "valle-fertil", "viaje", "merienda"],
    image: img.parador,
    imageAlt: "Paisaje abierto",
    mapsQuery: "Inna Café Laprida Mendoza Valle Fértil San Juan",
  },
  {
    slug: "panaderia-san-martin",
    name: "Panadería San Martín",
    kind: "panaderia",
    department: "albardon",
    locality: "Villa General San Martín",
    address: "La Paz, Villa General San Martín, Albardón",
    addressConfirmed: true,
    hours: "Mar–sáb 6–14 y 19:30–22 · Dom 6–14 · Lun cerrado. Tel. 0264 491-1804.",
    phone: "+54 264 491-1804",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Panadería de Albardón: facturas, semitas, tartas. El cafecito de departamento muchas veces empieza acá, no en un local con barra de especialidad.",
    story:
      "Albardón no tiene una peatonal de cafés. San Martín es el mostrador de Villa General San Martín: pan, facturas, merienda para llevar o para picar si hay lugar. Si la guía solo lista espresso, este departamento desaparece.",
    orderThis: ["Facturas", "Semitas", "Tarta"],
    tags: ["panaderia", "facturas", "albardon", "merienda"],
    image: img.delicias,
    imageAlt: "Facturas y pastelería",
    mapsQuery: "Panadería San Martín La Paz Villa General San Martín Albardón",
  },
  {
    slug: "dulce-alma",
    name: "Dulce Alma",
    kind: "panaderia",
    department: "chimbas",
    locality: "Chimbas",
    address: "5 de Octubre Oeste 56, Chimbas",
    addressConfirmed: true,
    hours: "Horario de panadería de barrio. Confirmá al +54 264 415-9768.",
    phone: "+54 264 415-9768",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Panadería de Chimbas: tartas, chocotorta, merienda de barrio. Chimbas casi no aparece si buscás “café San Juan”.",
    story:
      "Chimbas es denso y poco indexado para cafeterías. Dulce Alma es el tipo de local que sí existe: mostrador, dulce, vecinos. Un cafecito en Chimbas muchas veces es esto, no un brunch.",
    orderThis: ["Tarta", "Chocotorta", "Café si hay"],
    tags: ["panaderia", "chimbas", "merienda", "barrio"],
    image: img.isalu,
    imageAlt: "Torta",
    mapsQuery: "Dulce Alma 5 de Octubre 56 Chimbas San Juan",
  },
  {
    slug: "emi-len-krause",
    name: "Emi & Len",
    kind: "confiteria",
    department: "rawson",
    locality: "Villa Krause",
    address: "Mendoza Sur 4225, Villa Krause",
    addressConfirmed: true,
    hours: "Lun–vie ~7–13 y 17–21 · Sáb similar · Dom partido. Confirmá feriados.",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Panadería-confitería-café en Villa Krause. Facturas de mañana y merienda de barrio, lejos de la peatonal.",
    story:
      "Emi & Len combina mostrador y café. Está en Mendoza Sur, Rawson. Hay otra boca en Pocito: el nombre se repite porque es de barrio, no de cadena turística.",
    orderThis: ["Facturas", "Café", "Merienda"],
    tags: ["confiteria", "panaderia", "villa-krause", "merienda"],
    image: img.cinco,
    imageAlt: "Cafetería de barrio",
    mapsQuery: "Emi y Len Mendoza Sur 4225 Villa Krause San Juan",
  },
  {
    slug: "panaderia-cuyo",
    name: "Panadería Cuyo",
    kind: "panaderia",
    department: "pocito",
    locality: "Villa Aberastain",
    address: "Roberto Vidart 846, Villa Aberastain, Pocito",
    addressConfirmed: true,
    hours: "Suele atender de corrido. Tel. +54 264 463-8524.",
    phone: "+54 264 463-8524",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Panadería de Aberastain. En Pocito el cafecito a menudo es facturas en el mostrador, no un salón de especialidad.",
    story:
      "Pocito tiene pocos “cafés” en Google y muchas panaderías. Cuyo es una de ellas, en Roberto Vidart. Lo listamos para que Villa Aberastain no quede vacía en el mapa de merienda.",
    orderThis: ["Facturas", "Pan", "Algo dulce"],
    tags: ["panaderia", "pocito", "aberastain", "merienda"],
    image: img.delicias,
    imageAlt: "Pastelería",
    mapsQuery: "Panadería Cuyo Roberto Vidart Villa Aberastain Pocito",
  },
  {
    slug: "parque-pocito",
    name: "Heladería y Panadería del Parque",
    kind: "confiteria",
    department: "pocito",
    locality: "Pocito",
    address: "Av. Aberastain y Calle 11, local 4, Pocito",
    addressConfirmed: true,
    hours: "Consultá en el local: heladería, panadería y confitería de esquina.",
    visibility: "redes",
    sources: ["recorrido", "boca-en-boca"],
    blurb: "Esquina de Aberastain y 11: helado, pan y algo para merendar. Típico cafecito que no sale buscando “cafeterías San Juan”.",
    story:
      "En Pocito mucha gente merienda en la heladería-panadería de la esquina. Del Parque está en Aberastain y Calle 11. Es el formato que esta guía tiene que incluir si quiere ser honesta con el departamento.",
    orderThis: ["Café", "Facturas", "Helado"],
    tags: ["confiteria", "helado", "pocito", "merienda"],
    image: img.lisandro,
    imageAlt: "Helado",
    mapsQuery: "Heladería Panadería del Parque Aberastain Calle 11 Pocito",
  },
  {
    slug: "la-aldea",
    name: "La Aldea",
    kind: "confiteria",
    department: "santa-lucia",
    locality: "Santa Lucía",
    address: "Gral. José María Paz 2175, Santa Lucía",
    addressConfirmed: true,
    hours: "Confirmá por redes o al pasar: ficha de barrio, horarios de departamento.",
    visibility: "poco-conocido",
    sources: ["recorrido", "redes"],
    blurb: "Parada de Santa Lucía en José María Paz. El Gran San Juan también merienda a dos calles de Capital.",
    story:
      "Santa Lucía queda pegada a Capital y igual desaparece de las listas de cafés. La Aldea está en Paz 2175. Si conocés otro mostrador del departamento, sumalo: acá el hueco es enorme.",
    orderThis: ["Café", "Merienda"],
    tags: ["confiteria", "santa-lucia", "barrio", "merienda"],
    image: img.franklin,
    imageAlt: "Salón de café",
    mapsQuery: "La Aldea José María Paz 2175 Santa Lucía San Juan",
  },
  {
    slug: "cafe-chitos",
    name: "Café Chito's",
    kind: "cafe",
    department: "capital",
    locality: "Capital",
    address: "Francisco N. Laprida 169 Este, San Juan",
    addressConfirmed: true,
    hours: "Café de Laprida, a una cuadra de Franklin. Confirmá horario en el local.",
    visibility: "poco-conocido",
    sources: ["google", "recorrido"],
    blurb: "Café de Laprida: café con leche, medialunas y licuados. Clásico de vereda, no de tendencia.",
    story:
      "Chito's está en Laprida Este, cerca de otras confiterías de Capital. Lo sumamos para que el mapa de la ciudad no se reduzca a tres nombres de la peatonal.",
    orderThis: ["Café con leche", "Medialunas", "Licuado"],
    tags: ["cafe", "capital", "medialuna", "clasico"],
    image: img.haiti,
    imageAlt: "Taza de café",
    mapsQuery: "Café Chito's Laprida 169 Este San Juan",
  },
  {
    slug: "confiteria-paris",
    name: "Confitería París",
    kind: "confiteria",
    department: "capital",
    locality: "Capital",
    address: "Rivadavia 490, San Juan",
    addressConfirmed: true,
    hours: "Lun–sáb 8–21 · Dom 8–13. Tel. 0264 427-2787.",
    phone: "+54 264 427-2787",
    visibility: "conocido",
    sources: ["google", "recorrido"],
    blurb: "Confitería de Rivadavia: facturas, pan y merienda de mostrador con horario amplio.",
    story:
      "París es confitería de toda la vida en Rivadavia 490. Entra en la guía porque merendar en Capital también es esto: medialunas, miñón, mostrador familiar.",
    orderThis: ["Facturas", "Medialunas", "Café"],
    tags: ["confiteria", "capital", "facturas", "clasico"],
    image: img.montanas,
    imageAlt: "Pastelería",
    mapsQuery: "Confitería París Rivadavia 490 San Juan",
  },
  {
    slug: "thonet-cafe",
    name: "Thonet Café Restó",
    kind: "cafe",
    department: "capital",
    locality: "Capital",
    address: "Entre Ríos 221 Sur, San Juan",
    addressConfirmed: true,
    hours: "Consultá: resto-café de Entre Ríos. Tel. +54 264 427-4001.",
    phone: "+54 264 427-4001",
    visibility: "poco-conocido",
    sources: ["google", "recorrido"],
    blurb: "Café-restó en Entre Ríos Sur. Fuera de Tucumán y España, adentro de Capital.",
    story:
      "Thonet aparece en directorios locales y poco en las listas cortas. Entre Ríos 221: otro punto para merendar sin ir a la peatonal.",
    orderThis: ["Café", "Almuerzo liviano"],
    tags: ["cafe", "capital", "resto"],
    image: img.cleta,
    imageAlt: "Café",
    mapsQuery: "Thonet Café Entre Ríos 221 Sur San Juan",
  },
  {
    slug: "tres-cumbres",
    name: "Tres Cumbres Alfajores & Café",
    kind: "cafe",
    department: "capital",
    locality: "Capital",
    address: "Rivadavia 2, San Juan",
    addressConfirmed: true,
    hours: "Consultá sucursal: hay más de una boca (peatonal, clubes). Tel. +54 264 443-9714.",
    phone: "+54 264 443-9714",
    visibility: "conocido",
    sources: ["google", "redes"],
    blurb: "Alfajores sanjuaninos y café. Marca local con salón en Rivadavia.",
    story:
      "Tres Cumbres es de acá: alfajor y café. Lo listamos porque una guía de merienda en San Juan sin alfajor miente. Confirmá cuál sucursal está abierta el día que vayas.",
    orderThis: ["Alfajor", "Café"],
    tags: ["alfajor", "cafe", "capital", "merienda"],
    image: img.victoria,
    imageAlt: "Dulce artesanal",
    mapsQuery: "Tres Cumbres Alfajores Café Rivadavia 2 San Juan",
  },
  {
    slug: "augusto-media-agua",
    name: "Augusto",
    kind: "cafe",
    department: "sarmiento",
    locality: "Media Agua",
    address: "Media Agua, Sarmiento",
    addressConfirmed: false,
    hours: "Suele abrir de mañana al mediodía y a la noche. Confirmá en el pueblo: ficha digital floja.",
    visibility: "redes",
    sources: ["redes", "recorrido", "boca-en-boca"],
    blurb: "Café de Media Agua. En Sarmiento hay que preguntar: Google lista poco y el local se mueve en el pueblo.",
    story:
      "Sarmiento no existía en esta guía. Augusto es un café de Media Agua, con poca ficha y bastante boca en boca. Si sabés la calle, completala: el sur de la provincia también merienda.",
    orderThis: ["Café", "Algo dulce"],
    tags: ["cafe", "media-agua", "sarmiento", "redes"],
    image: img.lena,
    imageAlt: "Café latte",
    mapsQuery: "Augusto café Media Agua Sarmiento San Juan",
  },
  {
    slug: "pasteleria-la-nueva",
    name: "Pastelería La Nueva",
    kind: "pasteleria",
    department: "sarmiento",
    locality: "Media Agua",
    address: "Antonio Martínez López 260, Media Agua",
    addressConfirmed: true,
    hours: "Horario de pastelería de pueblo. Tel. +54 264 400-0125.",
    phone: "+54 264 400-0125",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Pastelería de Media Agua: facturas, medialunas, tortas. Merienda de Sarmiento sin subir a Capital.",
    story:
      "La Nueva está en Martínez López 260. No tiene web. Es exactamente el cafecito-pastelería que se pierde si la búsqueda se queda en el Gran San Juan.",
    orderThis: ["Facturas", "Medialunas", "Torta"],
    tags: ["pasteleria", "media-agua", "facturas", "merienda"],
    image: img.isalu,
    imageAlt: "Torta",
    mapsQuery: "Pastelería La Nueva Martínez López 260 Media Agua San Juan",
  },
  {
    slug: "helados-del-parque-caucete",
    name: "Helados del Parque",
    kind: "confiteria",
    department: "caucete",
    locality: "Caucete",
    address: "RN20 395, Caucete",
    addressConfirmed: true,
    hours: "Todos los días desde ~10 hasta la noche (más tarde vie–sáb). Tel. +54 264 488-7005.",
    phone: "+54 264 488-7005",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Heladería y cafetería sobre la diagonal de Caucete. Licuados, café y postre sin volver a Capital.",
    story:
      "Caucete no es solo Vallecito. Helados del Parque está en la RN20 y funciona también como cafetería. El este de la provincia merienda acá a la tarde, no en Tucumán.",
    orderThis: ["Café", "Licuado", "Helado"],
    tags: ["helado", "cafe", "caucete", "merienda"],
    image: img.lisandro,
    imageAlt: "Helado artesanal",
    mapsQuery: "Helados del Parque RN20 395 Caucete San Juan",
  },
  {
    slug: "cereza-libertador",
    name: "Cereza Libertador",
    kind: "restaurante",
    department: "capital",
    locality: "Desamparados",
    address: "Av. Libertador Gral. San Martín 1799 Oeste esquina Alvear, San Juan",
    addressConfirmed: true,
    hours: "Lun–vie 8 a 02 · Sáb 8:30 a 02 · Dom 8:30 a 00. Confirmá almuerzo y cena.",
    handle: "cereza.sanjuan",
    visibility: "conocido",
    sources: ["google", "recorrido"],
    blurb: "Café y resto local en la esquina de Libertador y Alvear. Desayuno, merienda y almuerzo ejecutivo en el mismo salón.",
    story:
      "Cereza es de acá: nació como confitería y esta sucursal ocupa la esquina que era Johnny B. Good. Maps la tira si buscás cafetería o restaurante en Desamparados. Vale para merendar y para comer, sin irte a la peatonal.",
    orderThis: ["Desayuno", "Almuerzo ejecutivo", "Café con tostado", "Merienda"],
    tags: ["merienda", "desayuno", "almuerzo", "cena", "libertador", "desamparados"],
    image: img.cinco,
    imageAlt: "Salón de cafetería iluminado",
    mapsQuery: "Cereza Libertador 1799 Oeste Alvear San Juan",
  },
  {
    slug: "cefferino",
    name: "Cefferino",
    kind: "cafe",
    department: "capital",
    locality: "Desamparados",
    address: "Av. José Ignacio de la Roza 2300 Oeste, San Juan",
    addressConfirmed: true,
    hours: "Lun–vie ~7:45 a 22 · Sáb desde las 9. Confirmá domingo.",
    phone: "+54 9 264 630-6323",
    handle: "cefferino.sj",
    visibility: "poco-conocido",
    sources: ["google", "recorrido"],
    blurb: "Café y patisserie sobre de la Roza. Más quieto que Libertador, con pastelería propia.",
    story:
      "Cefferino aparece en Maps si buscás café al oeste de Capital. No está en Tucumán: está en de la Roza, a metros de Vono. Café y pastelería, el tipo de local que el centro no te muestra aunque quede a diez cuadras.",
    orderThis: ["Café", "Pastelería", "Merienda"],
    tags: ["especialidad", "pasteleria", "merienda", "desamparados"],
    image: img.lena,
    imageAlt: "Café latte en mesa",
    mapsQuery: "Cefferino café de la Roza 2300 Oeste San Juan",
  },
  {
    slug: "vono-cafe",
    name: "Vono",
    kind: "restaurante",
    department: "capital",
    locality: "Desamparados",
    address: "Av. José Ignacio de la Roza 2321 Oeste, San Juan",
    addressConfirmed: true,
    hours: "Lun–vie 8–00:30 · Sáb–dom desde las 9 hasta 01. Desayuno, almuerzo, merienda y cena.",
    phone: "+54 264 426-4487",
    visibility: "conocido",
    sources: ["google", "recorrido"],
    blurb: "Café-bar de de la Roza que abre casi todo el día: merienda a la tarde, plato a la noche.",
    story:
      "Vono es de los resultados fijos si buscás cafetería o restaurante en este tramo de Capital. Horario corrido, mesa afuera, carta amplia. Lo listamos porque Desamparados merienda y come acá, no solo en la peatonal.",
    orderThis: ["Café", "Almuerzo", "Merienda"],
    tags: ["merienda", "desayuno", "almuerzo", "cena", "desamparados"],
    image: img.bonito,
    imageAlt: "Café espresso",
    mapsQuery: "Vono café de la Roza 2321 Oeste San Juan",
  },
  {
    slug: "tacu-resto",
    name: "Tacú Restó & Coffee",
    kind: "cafe",
    department: "capital",
    locality: "Desamparados",
    address: "Desamparados — sale en Maps y en el directorio local; confirmá la cuadra el día que vayas.",
    addressConfirmed: false,
    hours: "Confirmá por redes: café y resto de barrio.",
    visibility: "redes",
    sources: ["google", "recorrido"],
    blurb: "Café-restó de Desamparados. Circula más en el mapa del barrio que en las listas del centro.",
    story:
      "Tacú aparece cuando buscás cafetería en Desamparados. La ficha de calle todavía está floja, como varios locales al oeste de Circunvalación. Si sabés la dirección exacta, completala: es exactamente el tipo de hueco que esta guía quiere tapar.",
    orderThis: ["Café", "Almuerzo liviano"],
    tags: ["cafe", "almuerzo", "desamparados", "poco-indexado"],
    image: img.juana,
    imageAlt: "Interior de café moderno",
    mapsQuery: "Tacú Restó Coffee Desamparados San Juan",
  },
  {
    slug: "pizza-cafe-desamparados",
    name: "Pizza Cafe",
    kind: "cafe",
    department: "capital",
    locality: "Desamparados",
    address: "Desamparados — Maps y directorios locales lo listan; la calle hay que confirmarla.",
    addressConfirmed: false,
    hours: "Confirmá el día: café y pizza de barrio.",
    visibility: "poco-conocido",
    sources: ["google", "recorrido"],
    blurb: "El nombre lo dice: café y pizza en Desamparados. No es el circuito de Tucumán.",
    story:
      "Pizza Cafe (a veces Pi Zza Ca Fe) figura en las búsquedas de cafetería del oeste de Capital. Lo sumamos con la calle abierta: si lo encontraste andando, la guía lo necesita completo.",
    orderThis: ["Café", "Pizza"],
    tags: ["cafe", "pizza", "almuerzo", "desamparados"],
    image: img.comidas,
    imageAlt: "Pizza recién horneada",
    mapsQuery: "Pizza Cafe Desamparados San Juan",
  },
  {
    slug: "panetto",
    name: "Panetto",
    kind: "panaderia",
    department: "capital",
    locality: "Desamparados",
    address: "Desamparados, cerca de Victoria Igualada / Libertador oeste. Confirmá la cuadra.",
    addressConfirmed: false,
    hours: "Mar–dom ~8–13 y 16:30–20:30. Lunes suele cerrar.",
    handle: "panetto.gourmet",
    visibility: "poco-conocido",
    sources: ["google", "recorrido"],
    blurb: "Panadería gourmet de Desamparados. Facturas y pan para merendar sin bajar al microcentro.",
    story:
      "Panetto sale en Maps al lado de otras fichas de Libertador oeste. Es el mostrador que completa el mapa de merienda de Desamparados: no todo es café de especialidad.",
    orderThis: ["Facturas", "Pan", "Café si hay"],
    tags: ["panaderia", "facturas", "merienda", "desamparados"],
    image: img.delicias,
    imageAlt: "Facturas y pastelería",
    mapsQuery: "Panetto panadería Desamparados San Juan",
  },
  {
    slug: "del-parque-desamparados",
    name: "Del Parque Desamparados",
    kind: "confiteria",
    department: "capital",
    locality: "Desamparados",
    address: "Federico Cantoni Oeste, Desamparados",
    addressConfirmed: true,
    hours: "Horario de heladería-cafetería. Tel. +54 264 573-3410.",
    phone: "+54 264 573-3410",
    visibility: "poco-conocido",
    sources: ["google", "recorrido"],
    blurb: "Heladería y cafetería de Desamparados. Café y helado a la tarde, sin volver a la plaza.",
    story:
      "Hay más de un Del Parque en la provincia. Este está en Cantoni, Desamparados, y Maps lo muestra si buscás cafetería en el barrio. Helado, café, merienda de vereda.",
    orderThis: ["Café", "Helado", "Licuado"],
    tags: ["helado", "cafe", "merienda", "desamparados"],
    image: img.lisandro,
    imageAlt: "Helado artesanal",
    mapsQuery: "Del Parque heladería Federico Cantoni Desamparados San Juan",
  },
  {
    slug: "hostal-de-palito",
    name: "Hostal de Palito",
    kind: "restaurante",
    department: "capital",
    locality: "Desamparados",
    address: "Av. Circunvalación, lateral oeste 261 Sur, San Juan",
    addressConfirmed: true,
    hours: "Mié–sáb 21–01 · Dom 12:30–16. Lun y mar cerrado en este local. Confirmá el otro (Sirio Libanés).",
    phone: "+54 264 423-0105",
    handle: "palitoresto",
    visibility: "conocido",
    sources: ["google", "recorrido"],
    blurb: "Clásico sanjuanino de circunvalación: cocina regional e internacional, postres caseros, mesa de familia o de negocios.",
    story:
      "Si buscás restaurante en Maps alrededor de Libertador y Circunvalación, Palito aparece sí o sí. No es un secreto: es el resto que el sanjuanino ya tiene y esta guía también tiene que tener, al lado de los cafés del barrio.",
    orderThis: ["Cocina regional", "Popurrí árabe", "Postre casero"],
    tags: ["almuerzo", "cena", "clasico", "desamparados"],
    image: img.elizardo,
    imageAlt: "Mesa servida",
    mapsQuery: "Hostal de Palito Circunvalación 261 Sur San Juan",
  },
  {
    slug: "la-tapera",
    name: "La Tapera",
    kind: "restaurante",
    department: "capital",
    locality: "Desamparados",
    address: "Av. Circunvalación 105, entre Libertador y Paula Albarracín de Sarmiento",
    addressConfirmed: true,
    hours: "Confirmá el día. Tel. +54 264 423-2738.",
    phone: "+54 264 423-2738",
    visibility: "poco-conocido",
    sources: ["google", "recorrido"],
    blurb: "Restó de circunvalación, pegado a Libertador. Almuerzo o cena sin meterte al microcentro.",
    story:
      "La Tapera está en el mismo tramo de Maps que Palito y Rocknrolla. Es el tipo de resto que no entra en “cafeterías San Juan” y sí cuando buscás dónde comer al oeste de Capital.",
    orderThis: ["Almuerzo", "Minutas"],
    tags: ["almuerzo", "cena", "circunvalacion", "desamparados"],
    image: img.vallecito,
    imageAlt: "Mesa de comida",
    mapsQuery: "La Tapera restó Circunvalación 105 San Juan",
  },
  {
    slug: "rocknrolla",
    name: "Rocknrolla",
    kind: "restaurante",
    department: "capital",
    locality: "Desamparados",
    address: "Av. Libertador Gral. San Martín 2225 Oeste, San Juan",
    addressConfirmed: true,
    hours: "Bar y asador: noches largas. Tel. +54 264 426-8255.",
    phone: "+54 264 426-8255",
    visibility: "conocido",
    sources: ["google", "recorrido"],
    blurb: "Bar-pub con asador y minutas sobre Libertador. Más cena y birra que merienda.",
    story:
      "Rocknrolla sale en la búsqueda de restaurantes de este pin de Maps. Cocina de El Fogón de Roberto, carne a las llamas, carta amplia. Lo listamos para que “dónde comer” no sea solo un bodegón de mediodía.",
    orderThis: ["Carne a las llamas", "Minutas", "Cerveza"],
    tags: ["cena", "almuerzo", "parrilla", "libertador"],
    image: img.asado,
    imageAlt: "Asado a la parrilla",
    mapsQuery: "Rocknrolla Libertador 2225 Oeste San Juan",
  },
  {
    slug: "rinconcito-maloca",
    name: "El Rinconcito de Maloca",
    kind: "restaurante",
    department: "capital",
    locality: "Desamparados",
    address: "Desamparados, cerca de Libertador y Circunvalación. Confirmá la cuadra.",
    addressConfirmed: false,
    hours: "Confirmá: comida autóctona, horario de resto de barrio.",
    visibility: "poco-conocido",
    sources: ["google", "recorrido"],
    blurb: "Comida autóctona a metros de Libertador. El Maps del barrio lo tiene; las guías turísticas no.",
    story:
      "Maloca aparece al costado de las cafeterías si buscás restaurante en este tramo. Comida autóctona: exactamente el complemento de un café de especialidad. Si sabés la calle, sumala.",
    orderThis: ["Comida autóctona", "Plato del día"],
    tags: ["almuerzo", "cena", "regional", "desamparados"],
    image: img.regional,
    imageAlt: "Comida casera en la mesa",
    mapsQuery: "El Rinconcito de Maloca Desamparados San Juan",
  },
  {
    slug: "las-invernadas",
    name: "Las Invernadas Restó",
    kind: "restaurante",
    department: "capital",
    locality: "Desamparados",
    address: "Av. José Ignacio de la Roza 1946 Oeste, San Juan",
    addressConfirmed: true,
    hours: "Todos los días desde ~7:30 hasta pasada la medianoche. Desayuno, almuerzo, merienda y cena.",
    phone: "+54 264 426-6571",
    handle: "lasinvernadasresto",
    visibility: "conocido",
    sources: ["google", "recorrido"],
    blurb: "Bodegón de de la Roza que abre casi 18 horas. Porciones de resto, café a la mañana, cena tarde.",
    story:
      "Las Invernadas está en el mismo corredor que Vono y Cefferino. Maps lo lista como restaurante, pero también merendás. Es el formato sanjuanino de “un solo local para todo el día”.",
    orderThis: ["Almuerzo", "Menú del mediodía", "Café"],
    tags: ["almuerzo", "cena", "desayuno", "merienda", "bodegon"],
    image: img.grill,
    imageAlt: "Plato de restaurante",
    mapsQuery: "Las Invernadas Restó de la Roza 1946 Oeste San Juan",
  },
  {
    slug: "de-mono-rojo",
    name: "De Moño Rojo",
    kind: "restaurante",
    department: "capital",
    locality: "Desamparados",
    address: "Av. José Ignacio de la Roza 1826 Oeste, San Juan",
    addressConfirmed: true,
    hours: "Todos los días desde ~11 hasta medianoche (un poco más vie–sáb).",
    phone: "+54 264 463-0370",
    handle: "demonorojogrill",
    visibility: "conocido",
    sources: ["google", "recorrido"],
    blurb: "Grill y bar sobre de la Roza: carnes, almuerzo y cena. El Maps de restaurantes lo pone al lado de Las Invernadas.",
    story:
      "De Moño Rojo es parrilla, no confitería. Está en la búsqueda de restaurante del mismo pin. Lo incluimos porque la guía ahora también dice dónde comer, no solo dónde merendar.",
    orderThis: ["Grill", "Bife", "Almuerzo"],
    tags: ["almuerzo", "cena", "parrilla", "desamparados"],
    image: img.asado,
    imageAlt: "Carnes a la parrilla",
    mapsQuery: "De Moño Rojo grill de la Roza San Juan",
  },
  {
    slug: "bodegon-perico",
    name: "El Bodegón de Perico",
    kind: "restaurante",
    department: "capital",
    locality: "Desamparados",
    address: "Lateral de Circunvalación 379 Sur, San Juan",
    addressConfirmed: true,
    hours: "Confirmá: bodegón de circunvalación, horario de almuerzo y cena.",
    visibility: "poco-conocido",
    sources: ["google", "recorrido"],
    blurb: "Bodegón sobre el lateral de Circunvalación. Milanesa y plato del día, no brunch.",
    story:
      "Perico está a metros de Palito y La Tapera. Si Maps te tira restaurantes en este zoom, este es el bodegón del tramo. Complementa a los cafés de Libertador.",
    orderThis: ["Milanesa", "Plato del día"],
    tags: ["almuerzo", "cena", "bodegon", "circunvalacion"],
    image: img.grill,
    imageAlt: "Comida de bodegón",
    mapsQuery: "El Bodegón de Perico Circunvalación San Juan",
  },
  {
    slug: "resto-1592",
    name: "1592 Food & Drinks",
    kind: "restaurante",
    department: "capital",
    locality: "Desamparados",
    address: "Av. Libertador Gral. San Martín 1592 Oeste, San Juan",
    addressConfirmed: true,
    hours: "Confirmá por redes. Tel. +54 264 526-4541.",
    phone: "+54 264 526-4541",
    handle: "1592_bar",
    visibility: "poco-conocido",
    sources: ["google", "recorrido"],
    blurb: "Food & drinks sobre Libertador, entre el McDonald's y el centro. Más barra y plato que confitería.",
    story:
      "1592 aparece en la búsqueda de restaurante de Libertador oeste. Lo listamos para que el mapa de “dónde comer” no se quede solo en circunvalación: también hay mesa sobre la avenida.",
    orderThis: ["Barra", "Plato", "Algo para picar"],
    tags: ["almuerzo", "cena", "libertador", "bar"],
    image: img.clapton,
    imageAlt: "Barra de café y tragos",
    mapsQuery: "1592 Food Drinks Libertador 1592 Oeste San Juan",
  },
];

export const meriendaRoutes: MeriendaRoute[] = [
  {
    slug: "zonda-ullum",
    title: "Zonda y Ullum",
    subtitle: "La ruta que motiva esta guía",
    duration: "Una tarde",
    km: "Ida y vuelta desde Capital, ~40–60 km",
    placeSlugs: [
      "la-coqueta",
      "el-alba-zonda",
      "parque-parador-zonda",
      "cafe-haiti",
      "el-ensueno-ullum",
    ],
    why: "Cerro, dique y merienda de valle. Combiná una casa de té con ficha clara y las paradas de pueblo que se confirman el mismo día.",
  },
  {
    slug: "libertador",
    title: "Libertador, merienda al oeste",
    subtitle: "Rivadavia sin irte a la montaña",
    duration: "Medio día",
    km: "Por avenida, sin rutear",
    placeSlugs: ["entre-montanas", "casa-lena", "isalu-pasteleria"],
    why: "Casa de té, brunch de especialidad y pastelería de mostrador en la misma avenida. El Gran San Juan también es “departamento”.",
  },
  {
    slug: "barreal",
    title: "Barreal, té y cordillera",
    subtitle: "Calingasta un finde",
    duration: "Fin de semana",
    km: "~150 km desde Capital",
    placeSlugs: ["don-elizardo", "don-lisandro"],
    why: "Desayuno regional en Don Elizardo y helado o café en Don Lisandro. Confirmá el día anterior: Barreal no es peatonal Tucumán.",
  },
  {
    slug: "jachal",
    title: "Merienda en el norte",
    subtitle: "Jáchal tiene café de especialidad",
    duration: "Un día",
    km: "~150 km",
    placeSlugs: ["edesia-jachal", "marias-jachal"],
    why: "Edesia alcanza para justificar el viaje. Marías es el plan B de pueblo.",
  },
  {
    slug: "desamparados",
    title: "Desamparados, merienda y almuerzo",
    subtitle: "Libertador y circunvalación, sin bajar a la peatonal",
    duration: "Medio día",
    km: "Oeste de Capital, en auto o colectivo",
    placeSlugs: [
      "juana-house",
      "cereza-libertador",
      "cefferino",
      "hostal-de-palito",
      "las-invernadas",
    ],
    why: "El mismo pin de Maps: café de especialidad, Cereza para merendar o almorzar, y un clásico de circunvalación para comer.",
  },
];

export function getPlace(slug: string) {
  return places.find((place) => place.slug === slug);
}

export function placesByDepartment(id: string) {
  return places.filter((place) => place.department === id);
}
