import type { MeriendaRoute, Place } from "@/lib/types";

const img = {
  haiti:
    "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1400&q=80",
  coqueta:
    "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1400&q=80",
  alba:
    "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1400&q=80",
  ensueno:
    "https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=1400&q=80",
  punto:
    "https://images.unsplash.com/photo-1445116572660-236099ec97a0?auto=format&fit=crop&w=1400&q=80",
  cinco:
    "https://images.unsplash.com/photo-1493857671505-72967e2e2760?auto=format&fit=crop&w=1400&q=80",
  bendito:
    "https://images.unsplash.com/photo-1453614512568-7af50c6d2afb?auto=format&fit=crop&w=1400&q=80",
  franklin:
    "https://images.unsplash.com/photo-1521017432531-fbd92d768814?auto=format&fit=crop&w=1400&q=80",
  bonito:
    "https://images.unsplash.com/photo-1511920170033-f8396924c348?auto=format&fit=crop&w=1400&q=80",
  clapton:
    "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1400&q=80",
  montanas:
    "https://images.unsplash.com/photo-1481391319762-47dff72954d9?auto=format&fit=crop&w=1400&q=80",
  lena:
    "https://images.unsplash.com/photo-1497534446932-c925b458314e?auto=format&fit=crop&w=1400&q=80",
  cleta:
    "https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=1400&q=80",
  edesia:
    "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=1400&q=80",
  elizardo:
    "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1400&q=80",
  delicias:
    "https://images.unsplash.com/photo-1464305795204-6f5bbfc7fb81?auto=format&fit=crop&w=1400&q=80",
  isalu:
    "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=1400&q=80",
  juana:
    "https://images.unsplash.com/photo-1501339845172-3153c2184c68?auto=format&fit=crop&w=1400&q=80",
  parador:
    "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1400&q=80",
  rodeo:
    "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1400&q=80",
  lisandro:
    "https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=1400&q=80",
  gardel:
    "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=1400&q=80",
  comidas:
    "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=1400&q=80",
  marias:
    "https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=1400&q=80",
  victoria:
    "https://images.unsplash.com/photo-1571115177098-24ec42ed204d?auto=format&fit=crop&w=1400&q=80",
  vallecito:
    "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1400&q=80",
};

export const places: Place[] = [
  {
    slug: "cafe-haiti",
    name: "Café Haití",
    kind: "cafe",
    department: "ullum",
    locality: "Ullum",
    address:
      "Ubicación a confirmar — circula por Instagram y de boca en boca. Casi no aparece en Google Maps.",
    addressConfirmed: false,
    hours: "Confirmá por Instagram antes de ir: horarios de pueblo, a veces cierra sin aviso.",
    visibility: "instagram",
    sources: ["instagram", "recorrido", "boca-en-boca"],
    blurb:
      "El ejemplo de por qué hace falta esta guía: un café que la gente del departamento conoce y el resto de San Juan no.",
    story:
      "En los recorridos por Ullum y otros departamentos alejados del centro aparecen locales así: una vidriera chica, medialunas a la tarde, un cartel escrito a mano. Café Haití casi no está en Google, no tiene ficha turística y igual se llena los sábados porque alguien lo subió a una story. Esta ficha está incompleta a propósito: si sabés la calle, el horario o el @, sumalo. El punto no es “descubrirlo para turistas”: es que un sanjuanino de Capital también pueda merendar ahí.",
    orderThis: ["Café con leche", "Tostado", "Lo que haya salido del horno"],
    tags: ["poco-indexado", "instagram", "merienda", "departamento"],
    image: img.haiti,
    imageAlt: "Taza de café sobre mesa de madera",
    mapsQuery: "Ullum San Juan café",
  },
  {
    slug: "la-coqueta",
    name: "La Coqueta",
    kind: "casa-de-te",
    department: "zonda",
    locality: "Villa Basilio Nievas · Sierras Azules",
    address: "Ruta Provincial 12 esquina Sarmiento, Zonda",
    addressConfirmed: true,
    hours: "Lun–mié 10:30 a 18 · Jue cerrado · Vie–dom 10:30 a 02:00. Confirmá merienda por Instagram.",
    phone: "+54 264 439-9862",
    instagram: "lacoquetasanjuan",
    visibility: "conocido",
    sources: ["instagram", "google", "recorrido"],
    blurb: "Restaurante de campo y casa de té a 15 minutos de la ciudad, con merienda criolla y cerro de fondo.",
    story:
      "Andrea Coria lleva más de 15 años en Zonda. La Coqueta empezó cuando en el valle casi no había nada y hoy es el ancla del polo gastronómico (junto a Sierras Azules y Cielo Alto). No es un secreto absoluto, pero mucha gente de Capital sigue sin cruzar el dique a merendar. Vale el viaje: desayuno, almuerzo y merienda con paisaje, no con vidriera de peatonal.",
    orderThis: ["Merienda criolla", "Infusión", "Algo a las brasas si llegás al mediodía"],
    tags: ["merienda", "cerro", "patio", "fin-de-semana", "familia"],
    image: img.coqueta,
    imageAlt: "Cerros y valle de montaña al atardecer",
    mapsQuery: "La Coqueta RP12 Zonda San Juan",
  },
  {
    slug: "el-alba-zonda",
    name: "El Alba",
    kind: "comedor",
    department: "zonda",
    locality: "Zonda",
    address: "9 de Julio y Matías Sánchez, Zonda",
    addressConfirmed: true,
    hours: "Horario irregular: suele abrir lun–mié y domingo desde las 13. Jueves a sábado a menudo cerrado. Confirmá.",
    visibility: "poco-conocido",
    sources: ["recorrido", "instagram", "google"],
    blurb: "Casa de campo con postres y vista. Hermoso, pero hay que ir con el horario chequeado: no es una confitería de 8 a 21.",
    story:
      "El Alba aparece cuando recorrés Zonda y preguntás “¿dónde se merienda por acá?”. El lugar es precioso; la carta es corta y el servicio de merienda a veces se hace esperar. Lo incluimos porque es típico de los departamentos: un local que existe, que se ve en fotos, y que Google no te explica cuándo está abierto.",
    orderThis: ["Postre de la casa", "Café", "Entrada para picar"],
    tags: ["cerro", "postres", "horario-raro", "campo"],
    image: img.alba,
    imageAlt: "Montañas al sol",
    mapsQuery: "El Alba restaurante 9 de Julio Zonda San Juan",
  },
  {
    slug: "comidas-zonda",
    name: "COMIDAS..",
    kind: "comedor",
    department: "zonda",
    locality: "Zonda",
    address: "Zonda — ficha digital casi nula; preguntá en el pueblo o mirá si está la luz prendida.",
    addressConfirmed: false,
    hours: "Vie–dom de noche (aprox. 20 a 00). Cerrado lun–jue.",
    visibility: "instagram",
    sources: ["recorrido", "boca-en-boca"],
    blurb: "El nombre es el menú. Pizza a la piedra y platos de pueblo. Casi no tiene Instagram ni web: se encuentra yendo.",
    story:
      "COMIDAS.. es el extremo de lo que esta app quiere juntar: un local con nombre literal, horario de fin de semana y presencia digital cercana a cero. Quienes viven en Zonda lo tienen; quienes viven en Capital no. Si pasás el sábado a la noche, es una parada genuina.",
    orderThis: ["Pizza a la piedra", "Lo que salga"],
    tags: ["instagram", "fin-de-semana", "poco-indexado", "pueblo"],
    image: img.comidas,
    imageAlt: "Pizza recién horneada",
    mapsQuery: "COMIDAS Zonda San Juan",
  },
  {
    slug: "parque-parador-zonda",
    name: "Parque Parador de Montaña",
    kind: "confiteria",
    department: "zonda",
    locality: "Quebrada de Zonda",
    address: "Parque / parador de montaña, Quebrada de Zonda",
    addressConfirmed: true,
    hours: "Varía según temporada y concesión. Confirmá el día que vayas a la quebrada.",
    visibility: "poco-conocido",
    sources: ["recorrido", "facebook"],
    blurb: "Parador de la quebrada: café con vista, no con branding. Ideal si ya ibas al parque y no querías volver al centro con hambre.",
    story:
      "La Quebrada de Zonda es uno de los paisajes más queridos de la provincia. El parador y la hostería Sarmiento (en proceso de reconcesión) son exactamente el tipo de confitería que el turista busca y el local a veces olvida: merienda mirando el cerro. Lo listamos para que no dependa de que alguien lo suba a un reel.",
    orderThis: ["Café", "Tostado", "Agua + sombra"],
    tags: ["cerro", "merienda", "paseo", "quebrada"],
    image: img.parador,
    imageAlt: "Paisaje de montaña con cielo abierto",
    mapsQuery: "Parque Parador de Montaña Quebrada de Zonda San Juan",
  },
  {
    slug: "gardel-confiteria",
    name: "Gardel Confitería",
    kind: "confiteria",
    department: "zonda",
    locality: "Villa Basilio Nievas",
    address: "Villa Basilio Nievas, Zonda (camino sin nombre en Maps)",
    addressConfirmed: true,
    hours: "Mié–sáb 20:00 a 00:30. Lun, mar y dom cerrado. No es merienda: es noche.",
    phone: "+54 264 455-3794",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Se llama confitería y es una lomoteca de pueblo. Abre de noche. Lo metemos porque el nombre engaña y la gente de Zonda lo tiene como clásico.",
    story:
      "No todas las “confiterías” de departamento son medialunas a las 17. Gardel es el caso inverso: un local de lomos enormes, horario nocturno, y un nombre que en Capital nadie busca. Si armás una guía honesta, también tenés que decir cuándo NO ir a merendar.",
    orderThis: ["Lomo", "Cerveza"],
    tags: ["noche", "lomo", "pueblo", "no-merienda"],
    image: img.gardel,
    imageAlt: "Sándwich abundante",
    mapsQuery: "Gardel Confitería Villa Basilio Nievas Zonda",
  },
  {
    slug: "el-ensueno-ullum",
    name: "Comedor El Ensueño",
    kind: "comedor",
    department: "ullum",
    locality: "Ullum · Barrio Colón",
    address: "Calle San Antonio, Barrio Colón, Ullum",
    addressConfirmed: true,
    hours: "Lun–jue 8 a 14:30 y 20 a 23 · Domingo 9 a 14:30. Confirmá lunes feriados.",
    phone: "+54 264 414-1210",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Bodegón de Ullum que abre de mañana: desayuno y café sin pretender ser cafetería de especialidad.",
    story:
      "El Ensueño es de los pocos lugares de Ullum que aparecen con dirección. Sirve desayuno, almuerzo y cena, porciones de pueblo. Para quien recorre el dique y vuelve con hambre, es más útil que cualquier café de la peatonal. No lo vas a encontrar buscando “brunch San Juan”.",
    orderThis: ["Desayuno", "Comida casera", "Café"],
    tags: ["desayuno", "familia", "dique", "bodegon"],
    image: img.ensueno,
    imageAlt: "Interior cálido de cafetería",
    mapsQuery: "Comedor El Ensueño San Antonio Ullum San Juan",
  },
  {
    slug: "punto-encuentro-lm",
    name: "Punto de Encuentro L&M",
    kind: "cafe",
    department: "ullum",
    locality: "Ullum",
    address: "Ullum — maxikiosco / café de pueblo. Casi sin ficha digital.",
    addressConfirmed: false,
    hours: "Horario de comercio de pueblo. Preguntá en el lugar.",
    visibility: "instagram",
    sources: ["recorrido", "boca-en-boca"],
    blurb: "Maxikiosco que también es café. Cero Instagram activo, cero web. Se encuentra recorriendo Ullum.",
    story:
      "Hay un tipo de local sanjuanino que Google no sabe clasificar: vende galletitas, sirve un café, a veces un lomo, y es el punto de encuentro del barrio. Punto de Encuentro L&M es eso. Lo listamos porque si solo indexamos “cafeterías de especialidad”, Ullum desaparece del mapa.",
    orderThis: ["Café", "Algo de kiosco", "Lo que tengan caliente"],
    tags: ["poco-indexado", "pueblo", "instagram", "barrio"],
    image: img.punto,
    imageAlt: "Barra de café sencilla",
    mapsQuery: "Punto de Encuentro L&M Ullum San Juan",
  },
  {
    slug: "cinco-uno",
    name: "Cinco Uno Cafetería",
    kind: "cafe",
    department: "rawson",
    locality: "Villa Krause",
    address: "Pasaje Argentino 4288 Sur, Villa Krause",
    addressConfirmed: true,
    hours: "Lun–vie 8–13 y 18–21:30 · Sáb 8:30–13:30 y 18–21:30. Domingo: consultá stories.",
    phone: "+54 264 509-9996",
    instagram: "cincouno_cafeteria",
    visibility: "instagram",
    sources: ["instagram", "recorrido"],
    blurb: "Cafetería de Villa Krause que se mueve mucho por Instagram: desayunos, malteadas y sándwich de campo.",
    story:
      "Cinco Uno es el caso Capital-pero-no: está en el Gran San Juan y aun así vive en las redes. Desayunos, malteadas, sándwich de campo, tartas. Lo conocimos como se conocen estos lugares: un @, una story, un pasaje que no es avenida. Si buscás “cafeterías San Juan” te aparecen los de Tucumán y España; este no.",
    orderThis: ["Sándwich de campo", "Malteada", "Café", "Tarta"],
    tags: ["instagram", "desayuno", "merienda", "villa-krause"],
    image: img.cinco,
    imageAlt: "Cafetería iluminada de noche",
    mapsQuery: "Cinco Uno Cafetería Pasaje Argentino Villa Krause San Juan",
  },
  {
    slug: "entre-montanas",
    name: "Entre Montañas, casa de té y café",
    kind: "casa-de-te",
    department: "rivadavia",
    locality: "Rivadavia",
    address: "Av. Libertador Gral. San Martín 3790, Rivadavia",
    addressConfirmed: true,
    hours: "Mar–dom 9–13 y 17–22 · Lunes 17–22. Sábado a veces corrido.",
    phone: "+54 264 423-8556",
    visibility: "poco-conocido",
    sources: ["instagram", "google", "recorrido"],
    blurb: "Pastelería casera, infusiones y almuerzos livianos sobre Libertador. Más casa de té que café de moda.",
    story:
      "Rivadavia tiene una avenida entera de meriendas que Capital trata como “allá”. Entre Montañas es regional: scones, budines, infusiones, empanadas. Si armás una tarde hacia el oeste, es una parada clara antes o después de Zonda.",
    orderThis: ["Scones", "Infusión de la casa", "Budín", "Jugo natural"],
    tags: ["merienda", "pasteleria", "te", "libertador"],
    image: img.montanas,
    imageAlt: "Torta y chocolate",
    mapsQuery: "Entre Montañas casa de té Libertador 3790 Rivadavia San Juan",
  },
  {
    slug: "casa-lena",
    name: "Casa Lena",
    kind: "cafe",
    department: "rivadavia",
    locality: "Rivadavia",
    address: "Saavedra Norte 125, Rivadavia",
    addressConfirmed: true,
    hours: "Mar–dom 9–13 y 18–22. Lunes cerrado. Horarios según redes.",
    phone: "+54 264 662-4536",
    instagram: "casalenasj",
    visibility: "poco-conocido",
    sources: ["instagram", "google"],
    blurb: "Café de especialidad y brunch en Rivadavia, con mucha vida en Instagram.",
    story:
      "Casa Lena es de los pocos “coffee brunch” fuera de Capital. Saavedra Norte no es peatonal Tucumán: hay que ir a propósito. Café de especialidad, horarios partidos, y un @ que es la fuente de verdad de la carta.",
    orderThis: ["Café de especialidad", "Brunch", "Tostadas"],
    tags: ["especialidad", "brunch", "instagram", "merienda"],
    image: img.lena,
    imageAlt: "Café latte en mesa",
    mapsQuery: "Casa Lena Saavedra Norte 125 Rivadavia San Juan",
  },
  {
    slug: "isalu-pasteleria",
    name: "Isalú Pastelería",
    kind: "pasteleria",
    department: "rivadavia",
    locality: "Rivadavia",
    address: "Av. Libertador Gral. San Martín 7956, Rivadavia",
    addressConfirmed: true,
    hours: "Consultá por teléfono: +54 264 570-5551. Suele haber mostrador y delivery.",
    phone: "+54 264 570-5551",
    visibility: "poco-conocido",
    sources: ["google", "recorrido"],
    blurb: "Pastelería de Libertador: tortas, tartas, muffins. Más mostrador que salón, útil si vas de paso al oeste.",
    story:
      "No todo es café de especialidad. Isalú es el mostrador de barrio al que vas a buscar una tarta y te tomás algo si hay mesas. Este tipo de local es el tejido real de Rivadavia y casi nunca entra en “las 10 cafeterías de San Juan”.",
    orderThis: ["Tarta", "Torta", "Café para llevar"],
    tags: ["pasteleria", "para-llevar", "libertador"],
    image: img.isalu,
    imageAlt: "Torta de chocolate",
    mapsQuery: "Isalú Pastelería Libertador 7956 Rivadavia San Juan",
  },
  {
    slug: "bendito-cafe",
    name: "Bendito Café",
    kind: "cafe",
    department: "capital",
    locality: "Capital",
    address: "Rivadavia 249, pasillo interior, San Juan",
    addressConfirmed: true,
    hours: "Lun–vie 7 a 21 · Sáb 8:30–13 y 17–21 · Dom cerrado.",
    phone: "+54 264 626-7007",
    visibility: "conocido",
    sources: ["google", "instagram"],
    blurb: "Café de especialidad escondido en un pasillo del centro. Desayuno, brunch y almuerzo, lejos del ruido de la calle.",
    story:
      "Bendito es de Capital, pero ilustra el otro problema: incluso en el centro hay locales que no se ven desde la vereda. Está en un pasillo que conecta dos calles. Si esta guía solo listara Zonda, mentiría: el mapa incompleto también está a tres cuadras de la peatonal.",
    orderThis: ["Café de especialidad", "Brunch", "Pastelería"],
    tags: ["especialidad", "escondido", "desayuno", "centro"],
    image: img.bendito,
    imageAlt: "Café en interior iluminado",
    mapsQuery: "Bendito Café Rivadavia 249 San Juan",
  },
  {
    slug: "cafe-franklin",
    name: "Café Franklin",
    kind: "confiteria",
    department: "capital",
    locality: "Capital",
    address: "Francisco N. Laprida 63 Este, San Juan",
    addressConfirmed: true,
    hours: "Lun–vie 7:30–14 y 16:30/18–21 · Sáb similar · Dom cerrado.",
    visibility: "poco-conocido",
    sources: ["google", "recorrido"],
    blurb: "Confitería clásica cerca de la biblioteca: medialunas, suspiro de limón y café de toda la vida.",
    story:
      "Franklin no es un local de reel. Es el café de Laprida, con horario partido y cierre domingo —muy sanjuanino—. Lo incluimos para equilibrar: no todo lo “poco conocido” está en un departamento lejano; a veces está a una cuadra y no es tendencia.",
    orderThis: ["Medialunas", "Café con leche", "Suspiro de limón"],
    tags: ["clasico", "merienda", "centro", "confiteria"],
    image: img.franklin,
    imageAlt: "Salón de café clásico",
    mapsQuery: "Café Franklin Laprida 63 Este San Juan",
  },
  {
    slug: "bonito-cafe",
    name: "Bonito Café",
    kind: "cafe",
    department: "capital",
    locality: "Capital",
    address: "Av. España Sur 186, San Juan",
    addressConfirmed: true,
    hours: "Todos los días desde las 8 / 8:30 hasta 22:30 o 23.",
    phone: "+54 264 460-0888",
    visibility: "conocido",
    sources: ["google", "instagram"],
    blurb: "Café amplio sobre España: desayuno, merienda y platos para compartir. De los más visibles del centro.",
    story:
      "Bonito es un café amplio sobre España: desayuno, merienda y platos para compartir. De los más visitados de Capital, y parte de esta guía como el resto.",
    orderThis: ["Bonito desayuno", "Flat white", "Merienda para compartir"],
    tags: ["centro", "desayuno", "merienda", "amplio"],
    image: img.bonito,
    imageAlt: "Café espresso",
    mapsQuery: "Bonito Café España Sur 186 San Juan",
  },
  {
    slug: "clapton",
    name: "Clapton Café y Vinos",
    kind: "cafe",
    department: "capital",
    locality: "Capital",
    address: "Tucumán Sur 230, San Juan",
    addressConfirmed: true,
    hours: "Consultá: peatonal Tucumán, horarios amplios de café y vinos.",
    phone: "+54 264 422-8786",
    visibility: "conocido",
    sources: ["google", "instagram"],
    blurb: "Café de especialidad en Tucumán, con terraza. El circuito que sí aparece cuando buscás “cafeterías San Juan”.",
    story:
      "Clapton está en Tucumán con café de especialidad y terraza. Lo listamos junto a los locales de departamento porque la guía es de toda la provincia, no de un solo circuito.",
    orderThis: ["Café de origen", "Tostadas", "Algo de la terraza"],
    tags: ["especialidad", "centro", "terraza", "vinos"],
    image: img.clapton,
    imageAlt: "Granos de café tostado",
    mapsQuery: "Clapton Café Tucumán Sur 230 San Juan",
  },
  {
    slug: "cleta-cafe",
    name: "Cleta Café",
    kind: "cafe",
    department: "capital",
    locality: "Capital",
    address: "Av. Guillermo Rawson Sur 396, San Juan",
    addressConfirmed: true,
    hours: "Lun–vie 8:30–12:45 y 17–20:30 · Sáb solo mañana · Dom cerrado.",
    visibility: "poco-conocido",
    sources: ["google", "recorrido"],
    blurb: "Café sobre Rawson, horario partido y domingo cerrado. Fuera de la peatonal, cerca del estadio.",
    story:
      "Cleta está en Capital y igual se siente de barrio: cierra temprano, no abre domingo, y no está en Tucumán. Es el tipo de ficha que una guía de “los mejores cafés” se salta y un vecino usa todas las semanas.",
    orderThis: ["Café", "Merienda rápida"],
    tags: ["barrio", "horario-partido", "capital"],
    image: img.cleta,
    imageAlt: "Café en grano",
    mapsQuery: "Cleta Café Rawson Sur 396 San Juan",
  },
  {
    slug: "las-delicias",
    name: "Las Delicias Confitería",
    kind: "confiteria",
    department: "capital",
    locality: "Capital",
    address: "Av. Rioja Sur 148, San Juan",
    addressConfirmed: true,
    hours: "Lun–sáb 8–13 y 17–21 · Domingo cerrado.",
    phone: "+54 264 422-5519",
    visibility: "conocido",
    sources: ["google"],
    blurb: "Confitería de Rioja, frente a la Capilla San Clemente. Tradición de mostrador y salón.",
    story:
      "Las Delicias es el arquetipo de confitería sanjuanina de Capital: horario partido, domingo cerrado, facturas y café. Sirve de ancla para quien extraña “una confitería de verdad” y no un brunch.",
    orderThis: ["Facturas", "Café con leche", "Torta"],
    tags: ["confiteria", "clasico", "centro", "merienda"],
    image: img.delicias,
    imageAlt: "Facturas y pastelería",
    mapsQuery: "Las Delicias Confitería Rioja Sur 148 San Juan",
  },
  {
    slug: "juana-house",
    name: "Juana House",
    kind: "cafe",
    department: "capital",
    locality: "Desamparados",
    address: "Desamparados, Capital (confirmá la cuadra por Instagram)",
    addressConfirmed: false,
    hours: "Consultá redes: café de especialidad con horarios de barrio.",
    visibility: "instagram",
    sources: ["instagram", "facebook"],
    blurb: "Café de especialidad en Desamparados. Sale más en Instagram que en el mapa turístico del centro.",
    story:
      "Desamparados es Capital y no es el microcentro. Juana House aparece en directorios locales y en reels, no en las listas de “qué hacer en San Juan”. Lo listamos para empujar el mapa dos kilómetros al este.",
    orderThis: ["Café de especialidad", "Brunch chico"],
    tags: ["especialidad", "instagram", "desamparados"],
    image: img.juana,
    imageAlt: "Interior de café moderno",
    mapsQuery: "Juana House Café Desamparados San Juan",
  },
  {
    slug: "victoria-igualada",
    name: "Victoria Igualada",
    kind: "pasteleria",
    department: "capital",
    locality: "Desamparados",
    address: "Desamparados, Capital — pastelería artesanal y cafetería.",
    addressConfirmed: false,
    hours: "Consultá Instagram: obrador con horarios de retiro y salón acotado.",
    visibility: "instagram",
    sources: ["instagram", "facebook"],
    blurb: "Pastelería artesanal que se pide por redes. El salón, si abre, es un extra.",
    story:
      "Hay un circuito entero de pastelerías sanjuaninas que no son “local a la calle”: se encargan por WhatsApp, se retiran, a veces hay dos mesas. Victoria Igualada representa ese formato. Si esta guía solo listara salones, perderíamos la mitad de la oferta real.",
    orderThis: ["Torta de la semana", "Alfajores", "Café si hay salón"],
    tags: ["pasteleria", "instagram", "encargue", "desamparados"],
    image: img.victoria,
    imageAlt: "Torta artesanal",
    mapsQuery: "Victoria Igualada pastelería Desamparados San Juan",
  },
  {
    slug: "edesia-jachal",
    name: "Edesia",
    kind: "cafe",
    department: "jachal",
    locality: "San José de Jáchal",
    address: "Domingo F. Sarmiento 690, San José de Jáchal",
    addressConfirmed: true,
    hours: "Lun–vie 8:30–12 y 17:30–21:30 · Sáb–dom 9:30–13 y 17:30–21:30.",
    phone: "+54 264 471-4968",
    visibility: "poco-conocido",
    sources: ["instagram", "google", "recorrido"],
    blurb: "Café de especialidad en Jáchal. Para Capital es “el norte”; para Jáchal es el lugar a merendar.",
    story:
      "Edesia muestra que el café de especialidad también está en Jáchal. Tostadas, brunch y café bien hecho, en Sarmiento 690. Si alguien arma un finde al norte y solo busca parrilla, se pierde la merienda.",
    orderThis: ["Café de especialidad", "Tostada", "Brunch"],
    tags: ["especialidad", "norte", "merienda", "viaje"],
    image: img.edesia,
    imageAlt: "Taza de espresso",
    mapsQuery: "Edesia café Sarmiento 690 San José de Jáchal",
  },
  {
    slug: "marias-jachal",
    name: "Marías Restó Café Bar",
    kind: "cafe",
    department: "jachal",
    locality: "San José de Jáchal",
    address: "San José de Jáchal — restó café de pueblo.",
    addressConfirmed: false,
    hours: "Consultá el día: horarios de pueblo del norte.",
    visibility: "poco-conocido",
    sources: ["facebook", "recorrido"],
    blurb: "Café-bar de Jáchal que aparece en directorios locales y poco más. Complemento de Edesia para un día en el norte.",
    story:
      "Marías es el otro polo de Jáchal: menos “especialidad”, más restó café. Lo sumamos porque un departamento no puede tener una sola ficha y pretender que el mapa está completo.",
    orderThis: ["Café", "Algo salado"],
    tags: ["pueblo", "norte", "facebook"],
    image: img.marias,
    imageAlt: "Café filtrado",
    mapsQuery: "Marías Restó Café Bar Jáchal San Juan",
  },
  {
    slug: "don-elizardo",
    name: "Don Elizardo, casa de té",
    kind: "casa-de-te",
    department: "calingasta",
    locality: "Barreal",
    address: "Barreal, Calingasta — casa de té familiar (Liliana y Rebeca).",
    addressConfirmed: true,
    hours: "Pensado para desayunos y meriendas de quien llega a Barreal. Confirmá el día anterior.",
    visibility: "poco-conocido",
    sources: ["recorrido", "boca-en-boca", "facebook"],
    blurb: "Clásico familiar de Barreal: desayuno regional con cordillera. No es un café de Capital transplantado.",
    story:
      "Don Elizardo aparece en los circuitos turísticos de Calingasta y aun así mucha gente de San Juan ciudad no lo tiene en el radar. Desayuno regional, emprendimiento familiar, Barreal. Si el finde es Pampa del Leoncito, merendá acá —no en una estación de servicio de la ruta.",
    orderThis: ["Desayuno regional", "Té", "Algo casero"],
    tags: ["casa-de-te", "barreal", "familia", "viaje", "cordillera"],
    image: img.elizardo,
    imageAlt: "Mesa servida para desayuno",
    mapsQuery: "Don Elizardo casa de té Barreal Calingasta",
  },
  {
    slug: "don-lisandro",
    name: "Don Lisandro",
    kind: "confiteria",
    department: "calingasta",
    locality: "Barreal",
    address: "Barreal, Calingasta",
    addressConfirmed: true,
    hours: "Temporada de pueblo y jardín. Consultá +54 9 264 505-9122.",
    phone: "+54 9 264 505-9122",
    visibility: "poco-conocido",
    sources: ["instagram", "recorrido"],
    blurb: "Restó, heladería artesanal y jardín en Barreal. Postre o café después de la Pampa del Leoncito.",
    story:
      "Don Lisandro mezcla comida de pueblo, helado artesanal y patio. No es solo “un café”: es una razón para quedarse en Barreal a la tarde. Calingasta queda lejos para ir “a ver si está abierto”; por eso la ficha avisa que hay que confirmar.",
    orderThis: ["Helado artesanal", "Postre", "Café"],
    tags: ["helado", "barreal", "patio", "viaje"],
    image: img.lisandro,
    imageAlt: "Helado artesanal",
    mapsQuery: "Don Lisandro Barreal Calingasta San Juan",
  },
  {
    slug: "rodeo-cafe",
    name: "Rodeo Café Restó Bar",
    kind: "cafe",
    department: "iglesia",
    locality: "Rodeo",
    address: "Rodeo, Iglesia (ex Surfera)",
    addressConfirmed: true,
    hours: "Temporada de montaña. Confirmá por Facebook del pueblo.",
    visibility: "instagram",
    sources: ["facebook", "recorrido"],
    blurb: "Parada de Rodeo. La oferta de Iglesia se entera por Facebook, no por Google “cafeterías San Juan”.",
    story:
      "Iglesia es el ejemplo extremo: a horas de Capital, con un puñado de restós. Rodeo Café (ex Surfera) es de los pocos que figuran como café-bar. Si vas a Las Flores o al Parque Nacional San Guillermo, esta ficha evita que meriendes un paquete de galletitas en la ruta sin saber que había un local.",
    orderThis: ["Café", "Comida de parador"],
    tags: ["montana", "facebook", "viaje", "rodeo"],
    image: img.rodeo,
    imageAlt: "Camino de montaña",
    mapsQuery: "Rodeo Café Restó Bar Rodeo Iglesia San Juan",
  },
  {
    slug: "confiteria-vallecito",
    name: "Confitería de Vallecito",
    kind: "confiteria",
    department: "caucete",
    locality: "Vallecito · Paraje Difunta Correa",
    address: "Paraje Difunta Correa, Vallecito, Caucete",
    addressConfirmed: true,
    hours: "Días de movimiento del santuario y fines de semana. Confirmá si viajás entre semana.",
    visibility: "poco-conocido",
    sources: ["recorrido", "facebook"],
    blurb: "Confitería de ruta en el paraje de Difunta Correa. El turista para; el de Capital no la tiene como “salida a merendar”.",
    story:
      "Vallecito es un flujo enorme de gente y, aun así, la confitería del paraje no entra en ninguna guía de cafés. Es oferta real: café, facturas, algo salado, en el este de la provincia. Esta app también es para el que vuelve de Caucete y no quiere llegar a Capital para sentarse.",
    orderThis: ["Café", "Facturas", "Algo de ruta"],
    tags: ["ruta", "santuario", "este", "confiteria"],
    image: img.vallecito,
    imageAlt: "Mesa de comida de camino",
    mapsQuery: "Confitería Vallecito Difunta Correa Caucete San Juan",
  },
];

export const meriendaRoutes: MeriendaRoute[] = [
  {
    slug: "zonda-ullum",
    title: "Zonda y Ullum",
    subtitle: "La ruta que motiva esta guía",
    duration: "Una tarde",
    km: "Ida y vuelta desde Capital, ~40–60 km",
    placeSlugs: [
      "la-coqueta",
      "el-alba-zonda",
      "parque-parador-zonda",
      "cafe-haiti",
      "el-ensueno-ullum",
    ],
    why: "Cerro, dique y merienda de valle. Combiná una casa de té con ficha clara y las paradas de pueblo que se confirman el mismo día.",
  },
  {
    slug: "libertador",
    title: "Libertador, merienda al oeste",
    subtitle: "Rivadavia sin irte a la montaña",
    duration: "Medio día",
    km: "Por avenida, sin rutear",
    placeSlugs: ["entre-montanas", "casa-lena", "isalu-pasteleria"],
    why: "Casa de té, brunch de especialidad y pastelería de mostrador en la misma avenida. El Gran San Juan también es “departamento”.",
  },
  {
    slug: "barreal",
    title: "Barreal, té y cordillera",
    subtitle: "Calingasta un finde",
    duration: "Fin de semana",
    km: "~150 km desde Capital",
    placeSlugs: ["don-elizardo", "don-lisandro"],
    why: "Desayuno regional en Don Elizardo y helado o café en Don Lisandro. Confirmá el día anterior: Barreal no es peatonal Tucumán.",
  },
  {
    slug: "jachal",
    title: "Merienda en el norte",
    subtitle: "Jáchal tiene café de especialidad",
    duration: "Un día",
    km: "~150 km",
    placeSlugs: ["edesia-jachal", "marias-jachal"],
    why: "Edesia alcanza para justificar el viaje. Marías es el plan B de pueblo.",
  },
];

export function getPlace(slug: string) {
  return places.find((place) => place.slug === slug);
}

export function placesByDepartment(id: string) {
  return places.filter((place) => place.department === id);
}
