import type { Place } from "@/lib/types";

const img = {
  asado:
    "https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?auto=format&fit=crop&w=1400&q=80",
  bakery:
    "https://images.unsplash.com/photo-1464305795204-6f5bbfc7fb81?auto=format&fit=crop&w=1400&q=80",
  cafe: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1400&q=80",
  ice: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=1400&q=80",
  mountain:
    "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1400&q=80",
  pizza:
    "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=1400&q=80",
  regional:
    "https://images.unsplash.com/photo-1544025162-d76640320d2a?auto=format&fit=crop&w=1400&q=80",
  tea: "https://images.unsplash.com/photo-1497534446932-c925b458314e?auto=format&fit=crop&w=1400&q=80",
  herb: "https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?auto=format&fit=crop&w=1400&q=80",
  wine: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=1400&q=80",
  vegan:
    "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1400&q=80",
  sandwich:
    "https://images.unsplash.com/photo-1539252554453-80dab7ca82f8?auto=format&fit=crop&w=1400&q=80",
};

/** Locales de departamentos y herboristerías que Maps de Capital no indexa. */
export const provinciaPlaces: Place[] = [
  {
    slug: "kaktus-resto",
    name: "Kaktus Restó",
    kind: "restaurante",
    department: "albardon",
    locality: "El Topón · Albardón",
    address: "El Topón, Albardón. Confirmá la cuadra: OSM lo marca en Recabarren.",
    addressConfirmed: false,
    hours: "Suele abrir de noche (aprox. 20–02). Confirmá. Tel. +54 264 438-3972.",
    phone: "+54 264 438-3972",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Restó de Albardón: pachatas, milanesa y pileta en temporada. No está en la peatonal; está en el departamento.",
    story:
      "Si buscás restaurante en Albardón, Maps de Capital no te tira nada útil. Kaktus es el restó que el norte del Tulum sí tiene: bodegón, pachata, familia. Lo listamos para que Albardón no quede en una sola panadería.",
    orderThis: ["Pachata", "Milanesa", "Almuerzo"],
    tags: ["almuerzo", "cena", "albardon", "parrilla", "pachata"],
    image: img.regional,
    imageAlt: "Comida de restó",
    mapsQuery: "Kaktus Restó Albardón San Juan",
  },
  {
    slug: "cafe-1866",
    name: "1866 Café Bar",
    kind: "cafe",
    department: "albardon",
    locality: "El Rincón · Albardón",
    address: "El Rincón, Albardón",
    addressConfirmed: true,
    hours: "Confirmá: café-bar de departamento, no de peatonal.",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Café bar en El Rincón. El cafecito de Albardón no aparece buscando “cafeterías San Juan”.",
    story:
      "1866 está en El Rincón. OSM lo tiene; Google de Capital no. Es el tipo de bar-café que esta guía tiene que indexar si dice que cubre los 19 departamentos.",
    orderThis: ["Café", "Algo salado"],
    tags: ["cafe", "almuerzo", "albardon", "merienda"],
    image: img.cafe,
    imageAlt: "Café de barrio",
    mapsQuery: "1866 Café Bar Albardón San Juan",
  },
  {
    slug: "fruits-heladeria-albardon",
    name: "Fruits · Heladería del Parque",
    kind: "heladeria",
    department: "albardon",
    locality: "El Rincón · Albardón",
    address: "El Rincón, Albardón",
    addressConfirmed: true,
    hours: "Horario de heladería de barrio. Confirmá temporada.",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Helado en Albardón, no Grido de avenida. Maps de Capital no lo busca; el departamento sí lo tiene.",
    story:
      "Fruits aparece en el mapa abierto de Albardón. Heladería del parque de El Rincón. Si la guía solo lista Del Parque de Desamparados, miente sobre dónde se merienda al norte.",
    orderThis: ["Helado", "Cucurucho"],
    tags: ["helado", "merienda", "albardon"],
    image: img.ice,
    imageAlt: "Helado",
    mapsQuery: "Fruits Heladería del Parque Albardón San Juan",
  },
  {
    slug: "babobabs",
    name: "Babobabs",
    kind: "restaurante",
    department: "albardon",
    locality: "Villa General San Martín",
    address: "Arenales 396, Villa General San Martín, Albardón",
    addressConfirmed: true,
    hours: "Confirmá: comida saludable de Villa General San Martín.",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Comida saludable en Arenales. En Albardón también se almuerza sin milanesa.",
    story:
      "Babobabs está en Arenales 396. No es Capital: es Villa General San Martín. Lo sumamos para que “dónde comer” en Albardón no sea solo parrilla.",
    orderThis: ["Plato saludable", "Almuerzo"],
    tags: ["vegetariano", "almuerzo", "albardon"],
    image: img.vegan,
    imageAlt: "Comida saludable",
    mapsQuery: "Babobabs Arenales 396 Villa General San Martín Albardón",
  },
  {
    slug: "burbujas-reposteria",
    name: "Burbujas Repostería",
    kind: "pasteleria",
    department: "albardon",
    locality: "El Topón · Albardón",
    address: "El Topón, Albardón",
    addressConfirmed: true,
    hours: "Horario de repostería de barrio. Confirmá encargue.",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Repostería de El Topón. Merendar en Albardón a menudo es esto: mostrador, no especialidad.",
    story:
      "Burbujas está en Recabarren / El Topón. Maps de heladerías y cafés de Capital no la cruza. La merienda de Albardón pasa por acá.",
    orderThis: ["Torta", "Encargue"],
    tags: ["pasteleria", "merienda", "albardon"],
    image: img.bakery,
    imageAlt: "Repostería",
    mapsQuery: "Burbujas Repostería Albardón San Juan",
  },
  {
    slug: "herbosana",
    name: "Herbosana",
    kind: "herboristeria",
    department: "albardon",
    locality: "Villa General San Martín",
    address: "Villa General San Martín, Albardón",
    addressConfirmed: true,
    hours: "Horario de dietética de pueblo. Confirmá.",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Dietética-herboristería de Albardón. Yuyos e infusiones sin bajar a Capital.",
    story:
      "El pin de herboristerías de Maps se queda en Libertador. Herbosana está en Albardón. Si buscás yuyos en el departamento, esta es una boca.",
    orderThis: ["Infusión", "Yuyos", "Algo de dietética"],
    tags: ["herboristeria", "merienda", "albardon"],
    image: img.herb,
    imageAlt: "Hierbas e infusiones",
    mapsQuery: "Herbosana herboristería Albardón San Juan",
  },
  {
    slug: "patio-olmos-angaco",
    name: "Patio Gastronómico Olmos",
    kind: "comedor",
    department: "angaco",
    locality: "Angaco",
    address: "Angaco — circula como patio de eventos y comida. Confirmá fecha y predio.",
    addressConfirmed: false,
    hours: "No es un café de todos los días: confirmá si hay fecha. Angaco casi no tiene restó indexado.",
    visibility: "redes",
    sources: ["recorrido", "boca-en-boca"],
    blurb: "Lo poco que aparece si buscás comer en Angaco. Maps no lista pizzerías de Villa El Salvador; este patio sí circula.",
    story:
      "Angaco es de los 19 departamentos. OSM, en el pueblo, casi solo tira cadenas. El Patio Olmos es el nombre que sí circula para comer. La ficha está incompleta a propósito: si sabés la calle o un mostrador de lunes a sábado, sumalo. Sin eso, el este agrícola desaparece de la guía.",
    orderThis: ["Lo que arme el patio", "Empanadas si hay"],
    tags: ["almuerzo", "angaco", "poco-indexado", "redes"],
    image: img.regional,
    imageAlt: "Comida de patio",
    mapsQuery: "Patio Gastronómico Olmos Angaco San Juan",
  },
  {
    slug: "el-mercedario",
    name: "El Mercedario",
    kind: "restaurante",
    department: "calingasta",
    locality: "Barreal",
    address: "Presidente Julio A. Roca 1928, Barreal",
    addressConfirmed: true,
    hours: "Confirmá temporada de cordillera: restó de Barreal.",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Cocina local en Roca, Barreal. Almuerzo de valle, no de peatonal Tucumán.",
    story:
      "El Mercedario está en Roca 1928. Calingasta no es solo Don Elizardo: también se almuerza. Lo listamos para que “dónde comer” en Barreal tenga resto, no solo casa de té.",
    orderThis: ["Cocina regional", "Almuerzo"],
    tags: ["almuerzo", "cena", "barreal", "regional"],
    image: img.regional,
    imageAlt: "Comida de montaña",
    mapsQuery: "El Mercedario Roca 1928 Barreal Calingasta",
  },
  {
    slug: "la-casona-calingasta",
    name: "La Casona",
    kind: "restaurante",
    department: "calingasta",
    locality: "Villa Calingasta",
    address: "Aldo Cantoni, Villa Calingasta",
    addressConfirmed: true,
    hours: "Confirmá: restó de Villa Calingasta, no de Barreal.",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Restó en Villa Calingasta, sobre Cantoni. El valle no es un solo pueblo.",
    story:
      "Calingasta departamento también es Villa Calingasta, no solo Barreal. La Casona está en Cantoni. Si el mapa de merienda se queda en El Leoncito, este pueblo desaparece.",
    orderThis: ["Almuerzo", "Cocina de valle"],
    tags: ["almuerzo", "cena", "calingasta"],
    image: img.mountain,
    imageAlt: "Valle de Calingasta",
    mapsQuery: "La Casona Aldo Cantoni Villa Calingasta San Juan",
  },
  {
    slug: "los-del-norte",
    name: "Los del Norte",
    kind: "restaurante",
    department: "calingasta",
    locality: "Villa Calingasta",
    address: "Villa Calingasta",
    addressConfirmed: true,
    hours: "Confirmá. Tel. +54 264 575-6033.",
    phone: "+54 264 575-6033",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Restó de Villa Calingasta. Otra mesa para almorzar sin volver a Barreal.",
    story:
      "Los del Norte aparece en el mapa abierto del valle. Complementa a La Casona. Calingasta come en más de un pueblo.",
    orderThis: ["Almuerzo", "Minutas"],
    tags: ["almuerzo", "cena", "calingasta"],
    image: img.asado,
    imageAlt: "Mesa de restó",
    mapsQuery: "Los del Norte Villa Calingasta San Juan",
  },
  {
    slug: "quincho-el-nevado",
    name: "Quincho El Nevado",
    kind: "restaurante",
    department: "calingasta",
    locality: "Villa Calingasta",
    address: "Villa Calingasta",
    addressConfirmed: true,
    hours: "Confirmá. Tel. +54 9 264 673-1927.",
    phone: "+54 9 264 673-1927",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Quincho en Villa Calingasta. Asado y cocina argentina de valle.",
    story:
      "El Nevado es quincho, no café. En Calingasta “dónde comer” es esto: carne, mesa larga, cerro. Maps de Capital no lo busca.",
    orderThis: ["Asado", "Almuerzo"],
    tags: ["parrilla", "almuerzo", "cena", "calingasta"],
    image: img.asado,
    imageAlt: "Asado de quincho",
    mapsQuery: "Quincho El Nevado Villa Calingasta San Juan",
  },
  {
    slug: "juan-y-florinda",
    name: "Juan y Florinda",
    kind: "comedor",
    department: "calingasta",
    locality: "Parque Nacional El Leoncito",
    address: "Parque Nacional El Leoncito, Barreal",
    addressConfirmed: true,
    hours: "Suele abrir mañana y tarde; martes y miércoles a menudo cerrado. Confirmá. Tel. +54 264 527-6283.",
    phone: "+54 264 527-6283",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Proveeduría y comedor dentro de El Leoncito. Comida casera de parque, no de estación de servicio.",
    story:
      "Juan y Florinda está adentro del parque. Quien va a la Pampa del Leoncito come acá o no come. No es un secreto de Instagram: es el mostrador del valle. Confirmá el día: el parque no es peatonal.",
    orderThis: ["Comida casera", "Algo regional"],
    tags: ["almuerzo", "viaje", "cordillera", "barreal"],
    image: img.mountain,
    imageAlt: "Paisaje de El Leoncito",
    mapsQuery: "Juan y Florinda proveeduría Parque El Leoncito Barreal",
  },
  {
    slug: "kummel-barreal",
    name: "Kümmel",
    kind: "restaurante",
    department: "calingasta",
    locality: "Barreal",
    address: "Av. Pres. Roca, Barreal",
    addressConfirmed: true,
    hours: "Confirmá temporada: restó sobre Roca.",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Restó sobre Roca en Barreal. Otra mesa además de las casas de té.",
    story:
      "Kümmel aparece en las listas de gastronomía de Calingasta. Roca, Barreal. Lo sumamos para que el valle no se reduzca a dos nombres de merienda.",
    orderThis: ["Almuerzo", "Cena"],
    tags: ["almuerzo", "cena", "barreal"],
    image: img.regional,
    imageAlt: "Restó de Barreal",
    mapsQuery: "Kümmel restaurante Roca Barreal Calingasta",
  },
  {
    slug: "malevo-resto",
    name: "Malevo Restó & Parrilla",
    kind: "restaurante",
    department: "jachal",
    locality: "San José de Jáchal",
    address: "San Martín 727, San José de Jáchal",
    addressConfirmed: true,
    hours: "Confirmá. Tel. +54 9 264 740-6003.",
    phone: "+54 9 264 740-6003",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Parrilla en San Martín, Jáchal. El norte también cena asado, no solo café de especialidad.",
    story:
      "Malevo está en San Martín 727. Turismo provincial lo lista. Edesia cubre la merienda; Malevo el asado. Jáchal no es un solo local.",
    orderThis: ["Parrillada", "Almuerzo"],
    tags: ["parrilla", "almuerzo", "cena", "jachal"],
    image: img.asado,
    imageAlt: "Parrilla",
    mapsQuery: "Malevo Restó Parrilla San Martín 727 Jáchal",
  },
  {
    slug: "taberna-de-juan",
    name: "La Taberna de Juan",
    kind: "restaurante",
    department: "jachal",
    locality: "San José de Jáchal",
    address: "San Martín 656, frente a la plaza, San José de Jáchal",
    addressConfirmed: true,
    hours: "Almuerzo y cena de pueblo. Tel. +54 9 264 418-7785.",
    phone: "+54 9 264 418-7785",
    visibility: "conocido",
    sources: ["recorrido", "google"],
    blurb: "Bodegón frente a la plaza de Jáchal. Milanesa, pastas, menú del día.",
    story:
      "La Taberna de Juan es el bodegón de la plaza. Quien llega a Jáchal al mediodía come acá. No hace falta Maps de Capital: hace falta cruzar al norte.",
    orderThis: ["Menú del día", "Milanesa", "Pastas"],
    tags: ["almuerzo", "cena", "bodegon", "jachal"],
    image: img.regional,
    imageAlt: "Bodegón",
    mapsQuery: "La Taberna de Juan San Martín 656 Jáchal",
  },
  {
    slug: "buffet-punto-encuentro-jachal",
    name: "Buffet Punto de Encuentro",
    kind: "confiteria",
    department: "jachal",
    locality: "San José de Jáchal",
    address: "Av. Presidente Perón y Rivadavia, San José de Jáchal",
    addressConfirmed: true,
    hours: "Confirmá. Tel. +54 9 264 567-6410.",
    phone: "+54 9 264 567-6410",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Confitería-buffet en Perón y Rivadavia. Merienda de Jáchal además de Edesia.",
    story:
      "Punto de Encuentro está en el directorio de Turismo San Juan. Confitería de pueblo, no especialidad. El norte merienda acá también.",
    orderThis: ["Café", "Buffet", "Merienda"],
    tags: ["merienda", "almuerzo", "jachal", "confiteria"],
    image: img.bakery,
    imageAlt: "Confitería",
    mapsQuery: "Buffet Punto de Encuentro Perón Rivadavia Jáchal",
  },
  {
    slug: "herboristeria-san-cayetano",
    name: "Herboristería San Cayetano",
    kind: "herboristeria",
    department: "jachal",
    locality: "San José de Jáchal",
    address: "San José de Jáchal",
    addressConfirmed: true,
    hours: "Horario de herboristería de pueblo. Confirmá.",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Yuyos en Jáchal. El pin de herboristerías de Maps se queda en Capital; el norte tiene la suya.",
    story:
      "San Cayetano aparece en el mapa abierto de Jáchal. Infusiones y dietética de pueblo. Lo listamos para que “herboristerías” no sea solo Libertador.",
    orderThis: ["Yuyos", "Infusión"],
    tags: ["herboristeria", "jachal", "merienda"],
    image: img.herb,
    imageAlt: "Herboristería",
    mapsQuery: "Herboristería San Cayetano Jáchal San Juan",
  },
  {
    slug: "hosteria-huaco",
    name: "Hostería Huaco",
    kind: "restaurante",
    department: "jachal",
    locality: "Huaco",
    address: "Huaco, Jáchal",
    addressConfirmed: true,
    hours: "Confirmá: cocina regional de hostería de pueblo.",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Cocina regional en Huaco. Jáchal no es solo la villa cabecera.",
    story:
      "Huaco queda más adentro. La hostería sirve comida regional. Si el mapa se queda en San José de Jáchal, este paraje no existe.",
    orderThis: ["Cocina regional", "Almuerzo"],
    tags: ["almuerzo", "viaje", "jachal", "regional"],
    image: img.mountain,
    imageAlt: "Pueblo de Huaco",
    mapsQuery: "Hostería Huaco Jáchal San Juan",
  },
  {
    slug: "comedor-la-roca",
    name: "Comedor La Roca",
    kind: "comedor",
    department: "iglesia",
    locality: "Rodeo",
    address: "Rodeo, Iglesia",
    addressConfirmed: true,
    hours: "Horario de comedor de montaña. Confirmá el día: Rodeo no es peatonal.",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Comedor en Rodeo. Iglesia come acá; Maps de Capital no llega.",
    story:
      "La Roca está en Rodeo. Complementa a Rodeo Café. En Iglesia se almuerza en comedor, no en brunch.",
    orderThis: ["Almuerzo", "Comida de montaña"],
    tags: ["almuerzo", "iglesia", "rodeo"],
    image: img.regional,
    imageAlt: "Comedor de montaña",
    mapsQuery: "Comedor La Roca Rodeo Iglesia San Juan",
  },
  {
    slug: "cuesta-del-viento-parrilla",
    name: "Cuesta del Viento Parrilla",
    kind: "restaurante",
    department: "iglesia",
    locality: "Rodeo",
    address: "Rodeo, Iglesia",
    addressConfirmed: true,
    hours: "Confirmá temporada de dique y viento.",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Parrilla en Rodeo, al lado del dique. Iglesia también cena asado.",
    story:
      "Cuesta del Viento es el nombre del dique y de la parrilla. Quien sube a Rodeo a ver el lago come acá. No está en Libertador.",
    orderThis: ["Parrillada", "Almuerzo"],
    tags: ["parrilla", "almuerzo", "cena", "iglesia", "rodeo"],
    image: img.asado,
    imageAlt: "Parrilla de montaña",
    mapsQuery: "Cuesta del Viento Parrilla Rodeo Iglesia San Juan",
  },
  {
    slug: "donofrio-angualasto",
    name: "D'onofrio Confitería",
    kind: "confiteria",
    department: "iglesia",
    locality: "Angualasto",
    address: "Angualasto, Iglesia",
    addressConfirmed: true,
    hours: "Horario de pueblo. Confirmá: Angualasto no tiene ficha de Capital.",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Confitería en Angualasto. Iglesia es más que Rodeo.",
    story:
      "D'onofrio está en Angualasto. Si la guía de Iglesia solo lista Rodeo, miente. Merendar en el departamento a veces es este mostrador.",
    orderThis: ["Café", "Algo dulce"],
    tags: ["merienda", "iglesia", "confiteria"],
    image: img.bakery,
    imageAlt: "Confitería de pueblo",
    mapsQuery: "D'onofrio Confitería Angualasto Iglesia San Juan",
  },
  {
    slug: "encantos-de-rodeo",
    name: "Encantos de Rodeo",
    kind: "cafe",
    department: "iglesia",
    locality: "Rodeo",
    address: "Rodeo, Iglesia",
    addressConfirmed: true,
    hours: "Confirmá: café de Rodeo, temporada de montaña.",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Café en Rodeo además del Restó Bar. Iglesia merienda en más de un mostrador.",
    story:
      "Encantos de Rodeo aparece en el mapa abierto. Café de pueblo andino. Lo sumamos al lado de Rodeo Café para que el departamento no tenga una sola ficha de merienda.",
    orderThis: ["Café", "Merienda"],
    tags: ["merienda", "cafe", "iglesia", "rodeo"],
    image: img.tea,
    imageAlt: "Café de montaña",
    mapsQuery: "Encantos de Rodeo Iglesia San Juan",
  },
  {
    slug: "el-astiqueno",
    name: "El Astiqueño",
    kind: "restaurante",
    department: "valle-fertil",
    locality: "Villa San Agustín",
    address: "Villa San Agustín, Valle Fértil",
    addressConfirmed: true,
    hours: "Almuerzo de pueblo: llegá temprano si querés mesa.",
    visibility: "poco-conocido",
    sources: ["recorrido", "boca-en-boca"],
    blurb: "Parrilla y comida casera en San Agustín. Los locales almuerzan acá camino a Ischigualasto.",
    story:
      "El Astiqueño es el restó que recomiendan en Valle Fértil, no el café de guía. Carne a la parrilla, mesa de familia. Inna Café cubre la merienda; este el almuerzo.",
    orderThis: ["Parrillada", "Almuerzo"],
    tags: ["parrilla", "almuerzo", "cena", "valle-fertil"],
    image: img.asado,
    imageAlt: "Parrilla de pueblo",
    mapsQuery: "El Astiqueño Valle Fértil San Juan",
  },
  {
    slug: "cocina-zulma",
    name: "La Cocina de Zulma",
    kind: "comedor",
    department: "valle-fertil",
    locality: "Villa San Agustín",
    address: "Villa San Agustín, Valle Fértil",
    addressConfirmed: true,
    hours: "Almuerzo de pueblo. Pastas caseras: llegá temprano.",
    visibility: "poco-conocido",
    sources: ["recorrido", "boca-en-boca"],
    blurb: "Comedor de San Agustín, famoso por las pastas. Valle Fértil come en casa de Zulma, no en un brunch.",
    story:
      "Zulma es el otro nombre que se pasa de boca en boca en Valle Fértil. Pastas caseras. OSM lo escribe “zilma”: es el mismo mostrador. Confirmá el día.",
    orderThis: ["Pastas caseras", "Plato del día"],
    tags: ["almuerzo", "valle-fertil", "casero"],
    image: img.regional,
    imageAlt: "Pastas caseras",
    mapsQuery: "La Cocina de Zulma Valle Fértil San Juan",
  },
  {
    slug: "friends-valle-fertil",
    name: "Friends Restó",
    kind: "restaurante",
    department: "valle-fertil",
    locality: "Villa San Agustín",
    address: "Villa San Agustín, Valle Fértil",
    addressConfirmed: true,
    hours: "Confirmá: restó de pueblo camino a Ischigualasto.",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Restó en San Agustín. Otra mesa además del Astiqueño y Zulma.",
    story:
      "Friends aparece en el mapa abierto de Valle Fértil. Lo listamos para que el este no tenga dos fichas y un hueco enorme.",
    orderThis: ["Almuerzo", "Minutas"],
    tags: ["almuerzo", "cena", "valle-fertil"],
    image: img.regional,
    imageAlt: "Restó de pueblo",
    mapsQuery: "Friends Restó Valle Fértil San Juan",
  },
  {
    slug: "club-serrano",
    name: "Club Serrano",
    kind: "pizzeria",
    department: "valle-fertil",
    locality: "Villa San Agustín",
    address: "Rivadavia y Av. Ischigualasto, Villa San Agustín",
    addressConfirmed: true,
    hours: "Mar–dom; fines de semana hasta tarde. Confirmá.",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Pizzas, lomos y hamburguesas en Rivadavia e Ischigualasto. La noche de Valle Fértil.",
    story:
      "Club Serrano está en la esquina de Ischigualasto. Pizza de pueblo, no de Libertador. Valle Fértil también cena masa.",
    orderThis: ["Pizza", "Lomo"],
    tags: ["pizza", "cena", "almuerzo", "valle-fertil"],
    image: img.pizza,
    imageAlt: "Pizza",
    mapsQuery: "Club Serrano Rivadavia Ischigualasto Valle Fértil",
  },
  {
    slug: "heladeria-valle-de-la-luna",
    name: "Heladería Valle de la Luna",
    kind: "heladeria",
    department: "valle-fertil",
    locality: "Villa San Agustín",
    address: "Villa San Agustín, Valle Fértil",
    addressConfirmed: true,
    hours: "Horario de heladería de pueblo. Confirmá temporada.",
    visibility: "poco-conocido",
    sources: ["recorrido", "boca-en-boca"],
    blurb: "Helado artesanal de Valle Fértil: cidra, chocolate Ischigualasto, sabores de zona. No es Grido.",
    story:
      "Valle de la Luna (Mónica Rojas) hace helado con producto local y alfajor de orujo. Si merendás en Valle Fértil y no pedís cucurucho acá, te perdés el este.",
    orderThis: ["Helado de cidra", "Chocolate Ischigualasto"],
    tags: ["helado", "merienda", "valle-fertil", "artesanal"],
    image: img.ice,
    imageAlt: "Helado artesanal",
    mapsQuery: "Heladería Valle de la Luna Valle Fértil San Juan",
  },
  {
    slug: "comedor-ester",
    name: "Comedor de Ester",
    kind: "comedor",
    department: "valle-fertil",
    locality: "Chucuma",
    address: "Chucuma, Valle Fértil",
    addressConfirmed: true,
    hours: "Almuerzo de paraje. Confirmá: Chucuma no tiene horario de app.",
    visibility: "redes",
    sources: ["recorrido", "boca-en-boca"],
    blurb: "Comedor en Chucuma, camino a Ischigualasto. Pizza y pan casero de paraje.",
    story:
      "Ester está en Chucuma. Valle Fértil no es solo San Agustín. Si vas a los petroglifos, este es el almuerzo de ruta que Maps no pone primero.",
    orderThis: ["Almuerzo", "Pizza casera"],
    tags: ["almuerzo", "valle-fertil", "poco-indexado"],
    image: img.regional,
    imageAlt: "Comedor de paraje",
    mapsQuery: "Comedor de Ester Chucuma Valle Fértil San Juan",
  },
  {
    slug: "il-gato-caucete",
    name: "Il Gato",
    kind: "restaurante",
    department: "caucete",
    locality: "Caucete",
    address: "Caucete",
    addressConfirmed: true,
    hours: "Confirmá: restó de Caucete, cocina regional.",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Restó regional en Caucete. El este almuerza acá, no solo en Vallecito.",
    story:
      "Il Gato está en Caucete ciudad. Helados del Parque cubre la merienda; este el almuerzo. Caucete no es un santuario y una heladería.",
    orderThis: ["Cocina regional", "Almuerzo"],
    tags: ["almuerzo", "cena", "caucete", "regional"],
    image: img.regional,
    imageAlt: "Restó regional",
    mapsQuery: "Il Gato restaurante Caucete San Juan",
  },
  {
    slug: "vinoteca-la-bodeguita",
    name: "Vinoteca La Bodeguita",
    kind: "vinoteca",
    department: "caucete",
    locality: "Caucete",
    address: "Paula Albarracín de Sarmiento, Caucete",
    addressConfirmed: true,
    hours: "Horario de vinoteca de pueblo. Confirmá.",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Vinoteca en Caucete. El vino sanjuanino también se lleva en el este.",
    story:
      "La Bodeguita está en Paula Albarracín, Caucete. Las vinotecas de esta guía no pueden ser solo Libertador oeste.",
    orderThis: ["Botella sanjuanina", "Vino"],
    tags: ["vino", "vinoteca", "caucete"],
    image: img.wine,
    imageAlt: "Vinoteca",
    mapsQuery: "Vinoteca La Bodeguita Caucete San Juan",
  },
  {
    slug: "el-algarrobo-vallecito",
    name: "El Algarrobo",
    kind: "restaurante",
    department: "caucete",
    locality: "Vallecito",
    address: "Vallecito, local 18, Caucete",
    addressConfirmed: true,
    hours: "Horario de parador de santuario. Tel. +54 264 488-5096.",
    phone: "+54 264 488-5096",
    visibility: "conocido",
    sources: ["recorrido", "google"],
    blurb: "Parador en Vallecito: milanesa, pizza, helado, café. Donde para quien va a Difunta Correa.",
    story:
      "El Algarrobo es el restó del paraje. Confitería Vallecito cubre el café; este el plato. Quien cruza el este come acá aunque Google de Capital no lo busque.",
    orderThis: ["Milanesa", "Pizza", "Café"],
    tags: ["almuerzo", "cena", "merienda", "caucete", "ruta"],
    image: img.regional,
    imageAlt: "Parador de ruta",
    mapsQuery: "Restaurant El Algarrobo Vallecito Caucete San Juan",
  },
  {
    slug: "tierras-negras",
    name: "Tierras Negras Restó",
    kind: "restaurante",
    department: "pocito",
    locality: "Pocito",
    address: "Calle 11, Pocito",
    addressConfirmed: true,
    hours: "Confirmá. Tel. +54 264 565-6584.",
    phone: "+54 264 565-6584",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Restó en Calle 11, Pocito. Villa Aberastain almuerza acá, no solo en la panadería.",
    story:
      "Tierras Negras está en Calle 11. Pocito tiene panadería y heladería en el catálogo; faltaba el resto. Lo sumamos para que Aberastain también diga dónde comer.",
    orderThis: ["Almuerzo", "Cocina local"],
    tags: ["almuerzo", "cena", "pocito"],
    image: img.regional,
    imageAlt: "Restó de Pocito",
    mapsQuery: "Tierras Negras Restó Calle 11 Pocito San Juan",
  },
  {
    slug: "mundo-pizza-pocito",
    name: "Mundo Pizza",
    kind: "pizzeria",
    department: "pocito",
    locality: "Villa Aberastain",
    address: "Villa Aberastain, Pocito",
    addressConfirmed: true,
    hours: "Confirmá: pizza de Aberastain, más noche que merienda.",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Pizza en Aberastain. Pocito también cena muzza.",
    story:
      "Mundo Pizza está en Villa Aberastain. El Maps de pizzas de Libertador no llega. Esta es la masa de Pocito.",
    orderThis: ["Pizza", "Muzza"],
    tags: ["pizza", "cena", "almuerzo", "pocito"],
    image: img.pizza,
    imageAlt: "Pizza",
    mapsQuery: "Mundo Pizza Villa Aberastain Pocito San Juan",
  },
  {
    slug: "lomos-facha",
    name: "Lomos Facha",
    kind: "restaurante",
    department: "pocito",
    locality: "Villa Aberastain",
    address: "Av. Antonino Aberastain 207, Villa Aberastain",
    addressConfirmed: true,
    hours: "Confirmá: lomos y minutas de avenida.",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Lomos en Aberastain 207. Comer en Pocito también es esto.",
    story:
      "Facha está sobre Aberastain. No es confitería: es lomo. El departamento necesita fichas de cena, no solo facturas.",
    orderThis: ["Lomo", "Almuerzo"],
    tags: ["almuerzo", "cena", "pocito"],
    image: img.regional,
    imageAlt: "Lomo",
    mapsQuery: "Lomos Facha Aberastain 207 Pocito San Juan",
  },
  {
    slug: "heladin",
    name: "Heladín",
    kind: "heladeria",
    department: "sarmiento",
    locality: "Media Agua",
    address: "Media Agua, Sarmiento",
    addressConfirmed: true,
    hours: "Horario de heladería artesanal de pueblo. Confirmá.",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Helado artesanal en Media Agua. Sarmiento merienda cucurucho, no solo facturas de La Nueva.",
    story:
      "Heladín está en Media Agua. No listamos Grido de Ruta 40. Helado de pueblo, al sur de la provincia.",
    orderThis: ["Helado artesanal", "Cucurucho"],
    tags: ["helado", "merienda", "sarmiento", "artesanal"],
    image: img.ice,
    imageAlt: "Helado artesanal",
    mapsQuery: "Heladería Artesanal Heladín Media Agua Sarmiento",
  },
  {
    slug: "adolinda-los-berros",
    name: "Pan Casero y Semitas Adolinda",
    kind: "panaderia",
    department: "sarmiento",
    locality: "Los Berros",
    address: "Los Berros, Sarmiento",
    addressConfirmed: true,
    hours: "Horario de panadería de paraje. Confirmá.",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Pan y semitas en Los Berros. Sarmiento no es solo Media Agua.",
    story:
      "Adolinda está en Los Berros. Pedernal y Los Berros meriendan pan casero. Si la guía se queda en Media Agua, el departamento queda mentido.",
    orderThis: ["Semitas", "Pan casero"],
    tags: ["panaderia", "merienda", "sarmiento"],
    image: img.bakery,
    imageAlt: "Pan casero",
    mapsQuery: "Pan Casero Semitas Adolinda Los Berros Sarmiento",
  },
  {
    slug: "quincho-el-gringo",
    name: "Quincho El Gringo",
    kind: "restaurante",
    department: "sarmiento",
    locality: "Media Agua",
    address: "Media Agua, Sarmiento",
    addressConfirmed: true,
    hours: "Confirmá: quincho de pueblo, más finde que martes.",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Quincho en Media Agua. Sarmiento cena asado, no solo merienda pastelería.",
    story:
      "El Gringo está en Media Agua. Augusto y La Nueva cubren café y facturas; el quincho el almuerzo. El sur de Ruta 40 también come.",
    orderThis: ["Asado", "Almuerzo"],
    tags: ["parrilla", "almuerzo", "cena", "sarmiento"],
    image: img.asado,
    imageAlt: "Quincho",
    mapsQuery: "Quincho El Gringo Media Agua Sarmiento San Juan",
  },
  {
    slug: "suenos-del-sur",
    name: "Sueños del Sur",
    kind: "restaurante",
    department: "zonda",
    locality: "Zonda",
    address: "Libertad 90, Zonda",
    addressConfirmed: true,
    hours: "Confirmá. Tel. +54 299 548-7234.",
    phone: "+54 299 548-7234",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Restó en Libertad 90, Zonda. Cocina regional además de las casas de té.",
    story:
      "Sueños del Sur está en Libertad 90. Zonda no es solo La Coqueta. Acá se almuerza. Lo listamos para que el valle tenga resto, no solo merienda criolla.",
    orderThis: ["Cocina regional", "Almuerzo"],
    tags: ["almuerzo", "cena", "zonda", "regional"],
    image: img.mountain,
    imageAlt: "Restó de Zonda",
    mapsQuery: "Sueños del Sur Libertad 90 Zonda San Juan",
  },
  {
    slug: "abi-good",
    name: "Abi Good Resto Bar",
    kind: "restaurante",
    department: "zonda",
    locality: "Villa Tacú · Zonda",
    address: "Villa Tacú, Zonda",
    addressConfirmed: true,
    hours: "Confirmá: resto bar de Tacú.",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Resto bar en Villa Tacú. Zonda también cena del lado de Tacú, no solo en Sierras Azules.",
    story:
      "Abi Good está en Tacú. El departamento es más que la RP12. Lo sumamos para que Zonda no se reduzca a tres casas de té.",
    orderThis: ["Cena", "Almuerzo"],
    tags: ["almuerzo", "cena", "zonda"],
    image: img.regional,
    imageAlt: "Resto bar",
    mapsQuery: "Abi Good Resto Bar Villa Tacú Zonda San Juan",
  },
  {
    slug: "petras-marquesado",
    name: "Petra's",
    kind: "restaurante",
    department: "rivadavia",
    locality: "Marquesado",
    address: "Marquesado, Rivadavia",
    addressConfirmed: true,
    hours: "Confirmá: cocina regional de Marquesado.",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Restó en Marquesado. Rivadavia no es solo Libertador: La Bebida y Marquesado también comen.",
    story:
      "Petra's está en Marquesado. El zoom de Maps de herboristerías y pizzas se queda en de la Roza. Este es el resto del oeste, más adentro.",
    orderThis: ["Cocina regional", "Almuerzo"],
    tags: ["almuerzo", "cena", "rivadavia", "regional"],
    image: img.regional,
    imageAlt: "Restó de Marquesado",
    mapsQuery: "Petra's Marquesado Rivadavia San Juan",
  },
  {
    slug: "baires-1900",
    name: "Baires 1900",
    kind: "pizzeria",
    department: "santa-lucia",
    locality: "Santa Lucía",
    address: "Av. Libertador Gral. San Martín 3792 Este, Santa Lucía",
    addressConfirmed: true,
    hours: "Confirmá. Tel. +54 264 611-5218.",
    phone: "+54 264 611-5218",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Pizza y hamburguesa en Libertador Este. Santa Lucía también cena, no solo merienda en Paz.",
    story:
      "Baires 1900 está en Libertador 3792 Este. Santa Lucía tenía una sola ficha. Pizza del este de Capital, del otro lado de la avenida.",
    orderThis: ["Pizza", "Hamburguesa"],
    tags: ["pizza", "cena", "almuerzo", "santa-lucia"],
    image: img.pizza,
    imageAlt: "Pizza",
    mapsQuery: "Baires 1900 Libertador 3792 Este Santa Lucía San Juan",
  },
  {
    slug: "panchos-yiyo",
    name: "Panchos Yiyo",
    kind: "restaurante",
    department: "san-martin",
    locality: "Villa San Martín",
    address: "Tinto, Villa San Martín",
    addressConfirmed: true,
    hours: "Suele abrir solo mié ~20–00:30 y jue ~20:30–23:30. Confirmá: no es todos los días.",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Comida rápida de Villa San Martín, con horario de pueblo. El departamento San Martín sí come; Maps de Capital no lo busca.",
    story:
      "San Martín es uno de los 19 y no estaba en la guía. Yiyo está en Tinto. Abre poco: miércoles y jueves a la noche. Es exactamente el local que se pierde si buscás “restaurantes San Juan” en el centro.",
    orderThis: ["Lo que salga", "Cena de semana"],
    tags: ["cena", "san-martin", "horario-raro", "poco-indexado"],
    image: img.regional,
    imageAlt: "Comida de pueblo",
    mapsQuery: "Panchos Yiyo Tinto Villa San Martín San Juan",
  },
  {
    slug: "hobs-restobar",
    name: "Hobs Restobar",
    kind: "restaurante",
    department: "san-martin",
    locality: "Villa San Martín",
    address: "Luis Bustos, Villa San Martín",
    addressConfirmed: true,
    hours: "Confirmá el día: restobar de departamento, ficha digital floja.",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Restobar en Luis Bustos. Villa San Martín tiene barra; hay que preguntar si está abierto.",
    story:
      "Hobs está en Luis Bustos. San Martín departamento, no Albardón. Lo listamos con el horario abierto: en estos pueblos la luz prendida vale más que el mapa.",
    orderThis: ["Cena", "Birra"],
    tags: ["cena", "almuerzo", "san-martin", "poco-indexado"],
    image: img.cafe,
    imageAlt: "Restobar",
    mapsQuery: "Hobs Restobar Luis Bustos Villa San Martín San Juan",
  },
  {
    slug: "pilon-25-de-mayo",
    name: "Pilon",
    kind: "restaurante",
    department: "25-de-mayo",
    locality: "Villa Borjas",
    address: "Villa Borjas, 25 de Mayo",
    addressConfirmed: true,
    hours: "Confirmá: restó de Villa Borjas, sureste de la provincia.",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Restó en Villa Borjas. 25 de Mayo no aparece en el Maps de Capital; el pueblo sí come.",
    story:
      "Pilon está en Villa Borjas. 25 de Mayo era un hueco de la guía: ni departamento existía en el filtro. Este es un restó real del sureste.",
    orderThis: ["Almuerzo", "Minutas"],
    tags: ["almuerzo", "cena", "25-de-mayo"],
    image: img.regional,
    imageAlt: "Restó de pueblo",
    mapsQuery: "Pilon restaurante Villa Borjas 25 de Mayo San Juan",
  },
  {
    slug: "parador-punta-de-agua",
    name: "El Parador Punta de Agua",
    kind: "comedor",
    department: "25-de-mayo",
    locality: "Punta de Agua",
    address: "Punta de Agua, 25 de Mayo",
    addressConfirmed: true,
    hours: "Parador de ruta: confirmá si hay luz. No es un café de app.",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Parador en el sureste. Quien cruza 25 de Mayo merienda o almuerza acá, no en Tucumán.",
    story:
      "Punta de Agua es paraje. El parador es lo que hay. Lo listamos porque “los 19 departamentos” incluye esto: un mostrador de ruta que Maps de Libertador nunca va a tirar primero.",
    orderThis: ["Almuerzo de ruta", "Café si hay"],
    tags: ["almuerzo", "ruta", "25-de-mayo", "poco-indexado"],
    image: img.mountain,
    imageAlt: "Parador de ruta",
    mapsQuery: "El Parador Punta de Agua 25 de Mayo San Juan",
  },
  {
    slug: "entre-vinedos",
    name: "Entre Viñedos",
    kind: "bodega",
    department: "25-de-mayo",
    locality: "Villa Santa Rosa",
    address: "Calle 3 y Ruta 270, Villa Santa Rosa",
    addressConfirmed: true,
    hours: "Visitas de finca: mañana o atardecer. Reservá al +54 264 436-9013.",
    phone: "+54 264 436-9013",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Finca en Villa Santa Rosa: uva, vino, patay y alfajor de algarroba. 25 de Mayo merienda en el parral.",
    story:
      "Entre Viñedos es lo que Villa Santa Rosa sí tiene cuando no hay pizzería indexada: finca abierta, vino y algo dulce de algarroba. No es un café. Es cómo se merienda en 25 de Mayo si no querés mentirte.",
    orderThis: ["Uva del parral", "Vino", "Alfajor de algarroba"],
    tags: ["vino", "bodega", "ruta-del-vino", "merienda", "25-de-mayo", "familia"],
    image: img.wine,
    imageAlt: "Viñedo",
    mapsQuery: "Entre Viñedos Calle 3 Ruta 270 Villa Santa Rosa 25 de Mayo",
  },
  {
    slug: "raizal-aeropuerto",
    name: "Raizal",
    kind: "cafe",
    department: "9-de-julio",
    locality: "Aeropuerto · Las Chacritas",
    address: "Aeropuerto Domingo F. Sarmiento, 9 de Julio",
    addressConfirmed: true,
    hours: "Horario de aeropuerto. Confirmá si hay vuelo: no es un café de pueblo.",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Café en el aeropuerto, departamento 9 de Julio. Lo poco indexado que hay en Las Chacritas.",
    story:
      "9 de Julio casi no tiene restó en OSM. Raizal está en la terminal aérea. No es el cafecito de plaza que falta: es lo que el mapa sí tiene. Si conocés un mostrador en Alto de Sierra, sumalo: este departamento sigue corto.",
    orderThis: ["Café", "Algo rápido"],
    tags: ["cafe", "merienda", "9-de-julio", "ruta"],
    image: img.cafe,
    imageAlt: "Café",
    mapsQuery: "Raizal café aeropuerto San Juan 9 de Julio",
  },
  {
    slug: "gourmet-vinos-aeropuerto",
    name: "Gourmet & Vinos",
    kind: "vinoteca",
    department: "9-de-julio",
    locality: "Aeropuerto · Las Chacritas",
    address: "Aeropuerto Domingo F. Sarmiento, 9 de Julio",
    addressConfirmed: true,
    hours: "Horario de aeropuerto. Confirmá.",
    visibility: "poco-conocido",
    sources: ["recorrido", "google"],
    blurb: "Vino en el aeropuerto de 9 de Julio. Una botella sanjuanina antes de volar, no una vinoteca de Libertador.",
    story:
      "Gourmet & Vinos está en la misma terminal. 9 de Julio entra a la guía con lo que hay: aeropuerto. El hueco real es el pueblo. Completalo si sabés la panadería de Las Chacritas.",
    orderThis: ["Vino sanjuanino"],
    tags: ["vino", "vinoteca", "9-de-julio"],
    image: img.wine,
    imageAlt: "Vino",
    mapsQuery: "Gourmet y Vinos aeropuerto San Juan",
  },
  {
    slug: "palo-santo",
    name: "Palo Santo",
    kind: "herboristeria",
    department: "rivadavia",
    locality: "Rivadavia",
    address: "Rivadavia, cerca de Libertador oeste. Confirmá la cuadra.",
    addressConfirmed: false,
    hours: "Horario de herboristería. Tel. +54 264 502-6895.",
    phone: "+54 264 502-6895",
    visibility: "poco-conocido",
    sources: ["google", "recorrido"],
    blurb: "Herboristería del pin de Maps en Libertador oeste. Yuyos e infusiones, no café de especialidad.",
    story:
      "Palo Santo sale si buscás herboristerías en el zoom de Rivadavia. El Maps de Capital sí la encuentra; igual hay que listarla al lado de las de Jáchal y Albardón, para que el rubro no sea solo centro.",
    orderThis: ["Infusión", "Yuyos"],
    tags: ["herboristeria", "merienda", "rivadavia"],
    image: img.herb,
    imageAlt: "Herboristería",
    mapsQuery: "Palo Santo herboristería Rivadavia San Juan",
  },
  {
    slug: "herboristeria-andante",
    name: "Herboristería Andante",
    kind: "herboristeria",
    department: "rivadavia",
    locality: "Rivadavia",
    address: "Rivadavia, en el mismo zoom de herboristerías de Maps (~Libertador oeste).",
    addressConfirmed: false,
    hours: "Confirmá: hay más de una boca Andante en el Gran San Juan.",
    visibility: "poco-conocido",
    sources: ["google", "recorrido"],
    blurb: "Otra herboristería que tira el pin de Maps. Dietética de avenida, no de peatonal.",
    story:
      "Andante aparece dos veces en el mapa abierto. Esta ficha es la de Rivadavia, pegada al pin. Confirmá cuál boca está abierta.",
    orderThis: ["Yuyos", "Dietética"],
    tags: ["herboristeria", "merienda", "rivadavia"],
    image: img.herb,
    imageAlt: "Dietética",
    mapsQuery: "Herboristería Andante Rivadavia San Juan",
  },
  {
    slug: "herboristeria-cuyo",
    name: "Herboristería y Dietética Cuyo",
    kind: "herboristeria",
    department: "capital",
    locality: "Capital",
    address: "General Acha 12 Sur, San Juan",
    addressConfirmed: true,
    hours: "Horario de dietética de centro. Confirmá.",
    visibility: "conocido",
    sources: ["google", "recorrido"],
    blurb: "Dietética en Acha Sur. El Maps de herboristerías la pone en el centro; el resto de la guía cubre los departamentos.",
    story:
      "Cuyo está en Acha 12 Sur. Hay más sucursales. La listamos porque el pin de Maps la incluye, y porque merendar yuyos en Capital también es esto.",
    orderThis: ["Yuyos", "Infusión", "Dietética"],
    tags: ["herboristeria", "merienda", "capital"],
    image: img.herb,
    imageAlt: "Dietética",
    mapsQuery: "Herboristería Dietética Cuyo General Acha 12 Sur San Juan",
  },
  {
    slug: "la-esquina-saludable",
    name: "La Esquina Saludable",
    kind: "herboristeria",
    department: "capital",
    locality: "Desamparados",
    address: "Desamparados, Capital",
    addressConfirmed: true,
    hours: "Horario de tienda natural. Confirmá.",
    visibility: "poco-conocido",
    sources: ["google", "recorrido"],
    blurb: "Tienda natural en Desamparados. Sale en el mismo zoom de herboristerías.",
    story:
      "La Esquina Saludable está del lado de Desamparados. Complementa a Palo Santo: el pin de Maps no es una sola dietética.",
    orderThis: ["Infusión", "Algo natural"],
    tags: ["herboristeria", "merienda", "desamparados"],
    image: img.herb,
    imageAlt: "Tienda natural",
    mapsQuery: "La Esquina Saludable herboristería Desamparados San Juan",
  },
  {
    slug: "jacaranda-tienda",
    name: "Jacarandá Tienda Natural",
    kind: "herboristeria",
    department: "capital",
    locality: "Capital",
    address: "Capital, San Juan",
    addressConfirmed: true,
    hours: "Confirmá. Tel. +54 264 456-9146.",
    phone: "+54 264 456-9146",
    visibility: "poco-conocido",
    sources: ["google", "recorrido"],
    blurb: "Almacén natural. El Maps de herboristerías lo mezcla con las dietéticas de avenida.",
    story:
      "Jacarandá aparece en el mapa abierto de herboristerías. Productos naturales, no café. Lo listamos con el resto del rubro.",
    orderThis: ["Almacén natural", "Infusión"],
    tags: ["herboristeria", "merienda"],
    image: img.herb,
    imageAlt: "Almacén natural",
    mapsQuery: "Jacarandá Tienda Natural San Juan",
  },
  {
    slug: "de-raiz-almacen",
    name: "deRaíz",
    kind: "herboristeria",
    department: "capital",
    locality: "Capital",
    address: "Capital, San Juan",
    addressConfirmed: true,
    hours: "Horario de almacén medicinal. Confirmá.",
    visibility: "poco-conocido",
    sources: ["google", "recorrido"],
    blurb: "Almacén natural medicinal. Otra boca del zoom de herboristerías.",
    story:
      "deRaíz está en el mismo mapa. Yuyos y almacén, no restó. El pin de Maps junta estas fichas; la guía las nombra una por una.",
    orderThis: ["Yuyos", "Almacén"],
    tags: ["herboristeria", "merienda"],
    image: img.herb,
    imageAlt: "Almacén medicinal",
    mapsQuery: "deRaíz Almacén Natural Medicinal San Juan",
  },
  {
    slug: "inti-huasi",
    name: "Inti Huasi Almacén Natural",
    kind: "herboristeria",
    department: "capital",
    locality: "Capital",
    address: "Capital, San Juan",
    addressConfirmed: true,
    hours: "Horario de almacén natural. Confirmá.",
    visibility: "poco-conocido",
    sources: ["google", "recorrido"],
    blurb: "Almacén natural en Capital. Sale al buscar herboristerías en Maps.",
    story:
      "Inti Huasi completa el pin de herboristerías. No reemplaza a las de Jáchal o Albardón: convive. El rubro existe en toda la provincia, no solo en Acha.",
    orderThis: ["Almacén natural"],
    tags: ["herboristeria", "merienda"],
    image: img.herb,
    imageAlt: "Almacén natural",
    mapsQuery: "Inti Huasi Almacén Natural San Juan",
  },
  {
    slug: "pachatas-co-rivadavia",
    name: "Pachatas Co.",
    kind: "restaurante",
    department: "rivadavia",
    locality: "Rivadavia",
    address: "Av. Libertador Gral. San Martín 3390 Oeste, Rivadavia",
    addressConfirmed: true,
    hours: "Confirmá: pachatería sobre Libertador. Suele abrir a la noche.",
    visibility: "conocido",
    sources: ["google", "recorrido"],
    blurb: "Pachatas sobre Libertador, ya en Rivadavia. Es el local que tira el Maps si buscás pachatas en avenida.",
    story:
      "Pachatas Co. está en el mismo tramo de Libertador 3390 que El Canal Vegano. No es café: es sándwich sanjuanino. El pin de pachatas lo pone primero. Hay otra boca en 25 de Mayo Este.",
    orderThis: ["Pachata", "Sándwich"],
    tags: ["pachata", "almuerzo", "cena", "libertador"],
    image: img.sandwich,
    imageAlt: "Pachata",
    mapsQuery: "Pachatas Co Libertador 3390 Oeste Rivadavia San Juan",
  },
  {
    slug: "pachatas-co-capital",
    name: "Pachatas Co. · 25 de Mayo",
    kind: "restaurante",
    department: "capital",
    locality: "Capital",
    address: "25 de Mayo Este 400, San Juan",
    addressConfirmed: true,
    hours: "Confirmá: segunda boca, al este del centro.",
    visibility: "conocido",
    sources: ["google", "recorrido"],
    blurb: "La otra Pachatas Co.: 25 de Mayo Este, no Libertador. Misma pachata, otro barrio.",
    story:
      "Si el Maps de pachatas te deja en Rivadavia, esta boca está del lado este. 25 de Mayo 400. Completa el rubro en Capital sin mezclarlo con un café.",
    orderThis: ["Pachata"],
    tags: ["pachata", "almuerzo", "cena", "capital"],
    image: img.sandwich,
    imageAlt: "Pachata",
    mapsQuery: "Pachatas Co 25 de Mayo Este 400 San Juan",
  },
  {
    slug: "donata-del-desierto",
    name: "Donata Del Desierto",
    kind: "restaurante",
    department: "rivadavia",
    locality: "Rivadavia",
    address: "Av. Libertador Gral. San Martín 3311 Oeste, Rivadavia",
    addressConfirmed: true,
    hours: "Confirmá: pachata clásica sobre Libertador, a metros de Pachatas Co.",
    visibility: "poco-conocido",
    sources: ["google", "recorrido"],
    blurb: "Pachata clásica en Libertador 3311. Sale en el mismo zoom de pachatas, no es una franquicia.",
    story:
      "Donata está un poco antes que Pachatas Co. sobre Libertador. El Maps de pachatas las junta. La guía las nombra por separado: acá la pachata es de barrio, no de peatonal.",
    orderThis: ["Pachata clásica"],
    tags: ["pachata", "almuerzo", "cena", "libertador"],
    image: img.sandwich,
    imageAlt: "Pachata clásica",
    mapsQuery: "Donata Del Desierto Libertador 3311 Rivadavia San Juan",
  },
  {
    slug: "dorita-resto",
    name: "Dorita Restó",
    kind: "restaurante",
    department: "rivadavia",
    locality: "Barrio Posta del Ángel · Rivadavia",
    address: "Calcuta y Favaloro, Barrio Posta del Ángel, Rivadavia",
    addressConfirmed: true,
    hours: "Noche desde ~20:30. Lunes cerrado. Tel. +54 264 433-3752.",
    phone: "+54 264 433-3752",
    visibility: "poco-conocido",
    sources: ["google", "recorrido"],
    blurb: "Pachatas de noche en Posta del Ángel. No está sobre Libertador: está en el barrio.",
    story:
      "Dorita no aparece si buscás solo cafés. Calcuta y Favaloro, Posta del Ángel. Abre de noche; el lunes cierra. El pin de pachatas la incluye y la guía también.",
    orderThis: ["Pachata", "Cena"],
    tags: ["pachata", "cena", "almuerzo", "rivadavia"],
    image: img.sandwich,
    imageAlt: "Pachata de restó",
    mapsQuery: "Dorita Restó Calcuta Favaloro Posta del Ángel Rivadavia San Juan",
  },
  {
    slug: "ke-pachaton",
    name: "Ke Pachatón",
    kind: "restaurante",
    department: "chimbas",
    locality: "Chimbas",
    address: "Mendoza Norte 2143, Chimbas",
    addressConfirmed: true,
    hours: "Noche ~20–01:30. Tel. +54 264 507-8286.",
    phone: "+54 264 507-8286",
    visibility: "poco-conocido",
    sources: ["google", "recorrido"],
    blurb: "Pachatas en Chimbas. El Maps de Capital casi no llega; el departamento sí las pide de noche.",
    story:
      "Ke Pachatón está en Mendoza Norte, Chimbas. No es Libertador ni peatonal. Si esta guía dice pachatas y solo lista avenida, le falta el norte del Tulum.",
    orderThis: ["Pachata"],
    tags: ["pachata", "cena", "almuerzo", "chimbas"],
    image: img.sandwich,
    imageAlt: "Pachata",
    mapsQuery: "Ke Pachatón Mendoza Norte 2143 Chimbas San Juan",
  },
  {
    slug: "museo-graffigna",
    name: "Museo Santiago Graffigna",
    kind: "bodega",
    department: "capital",
    locality: "Desamparados",
    address: "Colón 1342 Norte, San Juan",
    addressConfirmed: true,
    hours: "Lun–sáb ~9–18 · Dom y feriados ~10–16. Confirmá. Tel. +54 264 421-4227.",
    phone: "+54 264 421-4227",
    visibility: "conocido",
    sources: ["google", "recorrido"],
    blurb: "La bodega más antigua de San Juan que sigue abierta. Museo, lagar y copa en Desamparados.",
    story:
      "El Maps de “rutas del vino, San Juan” abre en zoom 10 sobre Zonda–Ullum, pero Graffigna es la parada de ciudad: Colón Norte, museo y wine bar. No es una vinoteca de Libertador. Confirmá el horario del museo.",
    orderThis: ["Visita al museo", "Copa", "Syrah"],
    tags: ["vino", "bodega", "ruta-del-vino"],
    image: img.wine,
    imageAlt: "Copa de vino",
    mapsQuery: "Museo Santiago Graffigna Colón 1342 Norte San Juan",
  },
  {
    slug: "vinas-de-segisa",
    name: "Viñas de Segisa",
    kind: "bodega",
    department: "pocito",
    locality: "La Rinconada · Pocito",
    address: "Av. Aberastain entre calles 14 y 15, La Rinconada, Pocito",
    addressConfirmed: true,
    hours: "Confirmá visita. Tel. +54 264 492-2000.",
    phone: "+54 264 492-2000",
    visibility: "conocido",
    sources: ["google", "recorrido"],
    blurb: "Bodega boutique de Pocito, cavas subterráneas. Sale en el Maps de rutas del vino.",
    story:
      "Segisa está en La Rinconada, Aberastain entre 14 y 15. Es de las que el pin de rutas del vino tira cuando salís de Capital hacia Pocito. Reservá: no es un almacén de avenida.",
    orderThis: ["Visita", "Cata", "Cava"],
    tags: ["vino", "bodega", "ruta-del-vino", "pocito"],
    image: img.wine,
    imageAlt: "Bodega",
    mapsQuery: "Viñas de Segisa Aberastain Rinconada Pocito San Juan",
  },
  {
    slug: "champanera-miguel-mas",
    name: "Champañera Miguel Mas",
    kind: "bodega",
    department: "pocito",
    locality: "Pocito",
    address: "Calle 11, 500 m al este de Ruta 40, Pocito",
    addressConfirmed: true,
    hours: "Visitas con reserva. Tel. +54 264 660-4901.",
    phone: "+54 264 660-4901",
    visibility: "conocido",
    sources: ["google", "recorrido"],
    blurb: "Espumante orgánico en Pocito: recorrido, degüello y copa. Ruta del vino, no peatonal.",
    story:
      "Miguel Mas está sobre calle 11, a 500 metros de la 40. El Maps de rutas del vino la incluye. Orgánico, espumante, visita guiada. Llamá: no abras sin avisar.",
    orderThis: ["Espumante", "Visita", "Degustación"],
    tags: ["vino", "bodega", "ruta-del-vino", "pocito"],
    image: img.wine,
    imageAlt: "Espumante",
    mapsQuery: "Champañera Miguel Mas Calle 11 Pocito San Juan",
  },
  {
    slug: "las-marianas",
    name: "Bodega Las Marianas · Finca Camuñas",
    kind: "bodega",
    department: "pocito",
    locality: "La Rinconada · Pocito",
    address: "Calle Nueva entre Aberastain y Vidart, La Rinconada, Pocito",
    addressConfirmed: true,
    hours: "Confirmá visita. Tel. +54 9 264 566-9061.",
    phone: "+54 9 264 566-9061",
    visibility: "poco-conocido",
    sources: ["google", "recorrido"],
    blurb: "Bodega de más de 100 años al pie de la Sierra Chica de Zonda, en Pocito. Partidas chicas.",
    story:
      "Las Marianas / Finca Camuñas está en Calle Nueva, La Rinconada. El directorio de Turismo la pone en la Ruta del Vino. Confirmá: es finca, no vinoteca de Capital.",
    orderThis: ["Visita", "Vino", "Espumante"],
    tags: ["vino", "bodega", "ruta-del-vino", "pocito"],
    image: img.wine,
    imageAlt: "Viñedo de finca",
    mapsQuery: "Bodega Las Marianas Finca Camuñas Calle Nueva Pocito San Juan",
  },
  {
    slug: "finca-sierras-azules",
    name: "Finca Sierras Azules",
    kind: "bodega",
    department: "zonda",
    locality: "Zonda",
    address: "Sarmiento y Callejón Comunero, Zonda",
    addressConfirmed: true,
    hours: "Almuerzo y visita: reservá. Suele haber visita de lunes a viernes. Confirmá el día.",
    visibility: "conocido",
    sources: ["google", "recorrido"],
    blurb: "Bodega al pie de las Sierras Azules: almuerzo, copa y cerro. El Maps de rutas del vino la marca en Zonda.",
    story:
      "Sierras Azules queda a ~25 km de Capital, Sarmiento y Callejón Comunero. Es la bodega que el zoom de Zonda–Ullum tira para comer, no solo para catar. Reservá: el valle no atiende como la peatonal.",
    orderThis: ["Almuerzo", "Visita", "Copa"],
    tags: ["vino", "bodega", "ruta-del-vino", "almuerzo", "zonda"],
    image: img.wine,
    imageAlt: "Viñedos y cerro",
    mapsQuery: "Finca Sierras Azules Sarmiento Callejón Comunero Zonda San Juan",
  },
  {
    slug: "bodega-apotema",
    name: "Bodega Apotema",
    kind: "bodega",
    department: "zonda",
    locality: "Zonda",
    address: "Zonda, pie de montaña. Confirmá la finca: es posada y bodega.",
    addressConfirmed: false,
    hours: "Visita con reserva. WhatsApp +54 9 264 515-5433.",
    phone: "+54 9 264 515-5433",
    visibility: "poco-conocido",
    sources: ["google", "recorrido"],
    blurb: "Bodega boutique de Zonda, en la Ruta del Vino. Recorrido de parral, lagar y copa. Hay que reservar.",
    story:
      "Apotema está en el mismo valle que Sierras Azules. El Maps de rutas del vino la junta con el cerro. No es un restó de RP12: es visita. Escribí al WhatsApp antes de cruzar el dique.",
    orderThis: ["Visita guiada", "Cata", "Syrah"],
    tags: ["vino", "bodega", "ruta-del-vino", "zonda"],
    image: img.wine,
    imageAlt: "Parral",
    mapsQuery: "Bodega Apotema Zonda San Juan",
  },
  {
    slug: "bodegas-callia",
    name: "Bodegas Callia",
    kind: "bodega",
    department: "caucete",
    locality: "Caucete",
    address: "Calle de los Ríos s/n, Caucete",
    addressConfirmed: true,
    hours: "Mar–vie visitas ~9–12 y 14–16 · Sáb y feriados ~10–12 y 14–17. Tel. +54 264 496-2440.",
    phone: "+54 264 496-2440",
    visibility: "conocido",
    sources: ["google", "recorrido"],
    blurb: "Bodega grande de Caucete. El Tulum también es este: Callia no está en Pocito ni en Libertador.",
    story:
      "Callia está en Calle de los Ríos, Caucete. El pin de rutas del vino cubre Tulum entero; esta es la parada del este. Confirmá visita de grupo. No la confundas con una vinoteca de Capital.",
    orderThis: ["Visita", "Cata", "Callia Alta"],
    tags: ["vino", "bodega", "ruta-del-vino", "caucete"],
    image: img.wine,
    imageAlt: "Bodega",
    mapsQuery: "Bodegas Callia Calle de los Ríos Caucete San Juan",
  },
];
